// Histórico de versões do SentencifyAI
// Extraído do App.jsx para melhor organização

export const CHANGELOG = [
  { version: '1.37.28', feature: 'FASE 20: useFileHandling extraído para src/hooks/ (~594 linhas removidas) - getBulkPendingFilesCount, handleConfirmBulkCancel, generateModelsFromFileContent, processBulkFiles, handleBulkFileUpload, saveBulkModels, removeBulkReviewModel, toggleFavorite + bulk-prompts.ts' },
  { version: '1.37.27', feature: 'FASE 25: useSlashMenu extraído para src/hooks/ (~99 linhas removidas) - openSlashMenu, closeSlashMenu, navigateSlashMenu, selectModelFromSlash, updateSlashSearchTerm + useEffects' },
  { version: '1.37.26', feature: 'FASE 21: useDecisionExport extraído para src/hooks/ (~152 linhas removidas) - exportDecision para exportação da sentença com clipboard e HTML' },
  { version: '1.37.25', feature: 'FASE 18: useExportImport extraído para src/hooks/ (~204 linhas removidas) - exportAiSettings, importAiSettings, exportModels, importModels, checkDuplicate' },
  { version: '1.37.24', feature: 'FASE 17: useDetectEntities extraído para src/hooks/ (~243 linhas removidas) - detectarNomesAutomaticamente, constantes NER (STOP_WORDS_*, GENTILIC_WORDS, ORG_STOP_WORDS)' },
  { version: '1.37.23', feature: 'FASE 19: html-conversion.ts extraído para src/utils/ (~228 linhas removidas) - htmlToPlainText, htmlToFormattedText, plainTextToHtml, cleanHtmlForExport' },
  { version: '1.37.22', feature: 'FASE 16: useModelExtraction extraído para src/hooks/useModelExtraction.ts (~340 linhas removidas) - extractModelFromDecisionText, saveExtractedModel, cancelExtractedModel' },
  { version: '1.37.21', feature: 'FASE 15: useFactsComparison extraído para src/hooks/useFactsComparison.ts (~210 linhas removidas) - handleOpenFactsComparisonIndividual, handleGenerateFactsComparisonIndividual, estados e cache' },
  { version: '1.37.20', feature: 'FASE 14: injectQuillStyles + injectQuillLightStyles extraídos para src/utils/quill-styles-injector.ts (~390 linhas removidas)' },
  { version: '1.37.19', feature: 'Índice desatualizado removido do App.tsx (~95 linhas) - header simplificado aponta para estrutura modular (src/hooks, src/stores, src/components, etc.)' },
  { version: '1.37.18', feature: 'FASE 12-13: useDecisionTextGeneration + promptBuilders extraídos (~680 linhas removidas) - generateAiText, insertAiText, buildContextForChat, handleSendChatMessage, generateAiTextForModel + buildDocumentContentArray, buildMiniReportPrompt' },
  { version: '1.37.16', feature: 'FASE 11: useDispositivoGeneration extraído (~425 linhas removidas) - generateDispositivo, regenerateDispositivoWithInstruction movidos para src/hooks/useDispositivoGeneration.ts' },
  { version: '1.37.15', feature: 'Fix "Gerar com IA" (título/keywords): useModelGeneration agora lê conteúdo diretamente do Quill editor via modelEditorRef (antes usava modelLibrary.newModel.content que não sincroniza em tempo real)' },
  { version: '1.37.14', feature: 'FASE 10: useModelSave extraído (~380 linhas removidas) - saveModel, saveModelWithoutClosing, executeSaveModel, executeSaveAsNew, executeExtractedModelSave, processBulkSaveNext, handlers de similaridade movidos para src/hooks/useModelSave.ts' },
  { version: '1.37.13', feature: 'Remove cache de "Gerar com IA" (título/keywords) - cada clique gera nova resposta da IA (se o usuário clica de novo, é porque quer resposta diferente)' },
  { version: '1.37.12', feature: '(revertido em v1.37.13) Fix cache hit com clear→setTimeout→set' },
  { version: '1.37.11', feature: 'Fix "Gerar com IA" sync: ModelFormModal agora sincroniza localModel quando Zustand newModel.title/keywords mudam' },
  { version: '1.37.10', feature: 'Fix parcial useModelGeneration: stale closure em setNewModel corrigida com functional updater (prev => ...)' },
  { version: '1.37.9', feature: 'FASE 8 LegalDecisionEditor: useEmbeddingsManagement extraído (~400 linhas removidas) - importação, download CDN, limpeza e geração de embeddings (legislação, jurisprudência, modelos)' },
  { version: '1.37.8', feature: 'FASE 7 LegalDecisionEditor: useModelGeneration extraído (~155 linhas removidas) - generateKeywordsWithAI, generateTitleWithAI para geração de keywords/título via IA' },
  { version: '1.37.7', feature: 'FASE 6 LegalDecisionEditor: useTopicOperations extraído (~165 linhas removidas) - handleRenameTopic, handleMergeTopics, handleSplitTopic, handleCreateNewTopic + plainTextToHtml para utils/text.ts' },
  { version: '1.37.6', feature: 'FASE 5 LegalDecisionEditor: useDragDropTopics extraído (~183 linhas removidas) - handlers de drag & drop para tópicos principais e complementares' },
  { version: '1.37.5', feature: 'FASE 4 LegalDecisionEditor: useTopicOrdering extraído (~107 linhas removidas) - reorderTopicsViaLLM (Art. 337 CPC)' },
  { version: '1.37.4', feature: 'FASE 3 LegalDecisionEditor: useProofAnalysis extraído (~222 linhas removidas)' },
  { version: '1.37.3', feature: 'FASE 2 LegalDecisionEditor: useReportGeneration extraído (~314 linhas removidas)' },
  { version: '1.37.2', feature: 'FASE 1 LegalDecisionEditor: useDocumentAnalysis extraído (~1036 linhas removidas) - analyzeDocuments, handleCurationConfirm, etc.' },
  { version: '1.37.1', feature: 'FASE 7 refatoração final: ErrorBoundary extraído para src/components/ErrorBoundary.tsx (~152 linhas removidas)' },
  { version: '1.37.0', feature: 'FASE 6 refatoração final: src/styles/ criado com GlobalHoverStyles e ThemeStyles (~1316 linhas removidas)' },
  { version: '1.36.99', feature: 'FASE 5 refatoração final: GlobalEditorModal extraído para src/components/modals/ (~1572 linhas removidas)' },
  { version: '1.36.98', feature: 'FASE 4 refatoração final: LockedTabOverlay extraído para src/components/ui/ (~261 linhas removidas)' },
  { version: '1.36.97', feature: 'FASE 3 refatoração final: GlobalEditorSection e DecisionEditorContainer extraídos para src/components/editors/ (~370 linhas removidas)' },
  { version: '1.36.96', feature: 'FASE 2 refatoração final: prepareDocumentsContext, prepareProofsContext, prepareOralProofsContext, fastHashUtil extraídos para src/utils/context-helpers.ts (~260 linhas removidas)' },
  { version: '1.36.95', feature: 'FASE 1 refatoração final: CSS, RESULTADO_STYLES extraídos para src/constants/styles.ts + INSTRUCAO_NAO_PRESUMIR extraído para src/prompts/instrucoes.ts (~90 linhas removidas)' },
  { version: '1.36.94', feature: 'Quill Editors + TIER 3 pendências extraídos: QuillEditorBase, QuillModelEditor, QuillDecisionEditor, QuillMiniRelatorioEditor, AIRegenerationSection, FieldEditor, InlineFormattingToolbar, ModelFormModal, ModelPreviewModal (~1787 linhas removidas)' },
  { version: '1.36.93', feature: 'TIER 3 componentes extraídos: ModelFormFields (forms/), SlashCommandMenu (ui/), JurisprudenciaModal (modals/) (~616 linhas removidas)' },
  { version: '1.36.92', feature: 'TIER 2 modais extraídos para AdvancedModals.tsx: ShareLibraryModal, AcceptSharePage, DispositivoModal, BulkReviewModal, BulkUploadModal (~1215 linhas removidas)' },
  { version: '1.36.91', feature: 'TIER 1 modais extraídos para MiscModals.tsx: AnalysisModal, ExportModal, AnonymizationNamesModal, LinkedProofsModal (~288 linhas removidas)' },
  { version: '1.36.90', feature: 'AI Assistant components extraídos para src/components/ai/: AIAssistantBaseLegacy, AIAssistantBase, AIAssistantModal, AIAssistantGlobalModal, AIAssistantModelModal + helpers (extractPlainText, isOralProof, hasOralProofsForTopic) (~685 linhas removidas)' },
  { version: '1.36.89', feature: 'Proof modals extraídos: ProofAnalysisModal, LinkProofModal adicionados a ProofModals.tsx (~230 linhas removidas)' },
  { version: '1.36.88', feature: 'Model extraction modals extraídos: ExtractModelConfirmModal, ExtractedModelPreviewModal, SimilarityWarningModal (~290 linhas removidas)' },
  { version: '1.36.87', feature: 'Panel components extraídos para src/components/panels/: FullscreenModelPanel, ModelSearchPanel, JurisprudenciaTab, LegislacaoTab (~1160 linhas removidas)' },
  { version: '1.36.86', feature: 'Card components extraidos para src/components/cards/: TopicCard, SortableTopicCard, ModelCard, ProofCard, VirtualList (~1140 linhas removidas)' },
  { version: '1.36.85', feature: 'Modais simples extraídos para src/components/modals/: BaseModal, ModalFooter, ModalWarningBox, ModalInfoBox, ModalAmberBox, ModalContentPreview + TopicModals, ModelModals, ProofModals, SessionModals, BulkModals, TextPreviewModal (~580 linhas removidas)' },
  { version: '1.36.84', feature: 'Chat components extraídos: ChatBubble, ChatHistoryArea, ChatInput, InsertDropdown para src/components/chat/ (~185 linhas removidas)' },
  { version: '1.36.83', feature: 'Mais UI components extraídos: VersionCompareModal, VersionSelect para src/components/version/ + JurisprudenciaCard, ArtigoCard para src/components/cards/ (~460 linhas removidas)' },
  { version: '1.36.82', feature: 'UI components extraídos: SuggestionCard, SplitDivider para src/components/cards/ + SpacingDropdown, FontSizeDropdown, ProcessingModeSelector para src/components/ui/ (~147 linhas removidas)' },
  { version: '1.36.81', feature: 'Serviços e utilitários extraídos: EmbeddingsServices.ts (~540 linhas), jurisprudencia.ts (~420 linhas), text.ts (~200 linhas), models.ts (~30 linhas) - App.tsx reduzido para ~28,900 linhas' },
  { version: '1.36.80', feature: 'useAIIntegration extraído para src/hooks/ (~1310 linhas removidas) + API_BASE extraído para src/constants/api.ts' },
  { version: '1.36.79', feature: 'useQuillEditor e useDocumentServices extraídos para src/hooks/ (~30KB removidos) + sanitizeQuillHTML' },
  { version: '1.36.78', feature: 'useModalManager e useModelLibrary extraídos para src/hooks/ (~14KB removidos) + searchModelsInLibrary, removeAccents, SEARCH_STOPWORDS, SINONIMOS_JURIDICOS' },
  { version: '1.36.77', feature: 'useTopicManager extraído para src/hooks/ (wrapper sobre Zustand store)' },
  { version: '1.36.76', feature: 'useProofManager e useDocumentManager extraídos para src/hooks/ (~486 linhas removidas)' },
  { version: '1.36.75', feature: 'useLocalStorage extraído para src/hooks/ (~1070 linhas removidas) + PDF IndexedDB helpers + APP_VERSION centralizado' },
  { version: '1.36.74', feature: 'useModelPreview extraído para src/hooks/ (~107 linhas removidas)' },
  { version: '1.36.73', feature: 'useChatAssistant extraído para src/hooks/ (~115 linhas removidas) + MAX_CHAT_HISTORY_MESSAGES' },
  { version: '1.36.72', feature: 'useJurisprudencia extraído para src/hooks/ (~210 linhas removidas) + helpers (IRR_TYPES, isIRRType, JURIS_TIPOS_DISPONIVEIS, JURIS_TRIBUNAIS_DISPONIVEIS, IndexedDB helpers)' },
  { version: '1.36.71', feature: 'useLegislacao extraído para src/hooks/ (~180 linhas removidas) + helpers (LEIS_METADATA, getLeiFromId, sortArtigosNatural, IndexedDB helpers)' },
  { version: '1.36.70', feature: 'Testes REAIS para 9 hooks extraídos (411 testes passando), regra #10 CLAUDE.md (testes devem importar código de produção), deletados 6 testes inefetivos' },
  { version: '1.36.69', feature: 'FASE 3 TIER 1: useIndexedDB extraído para src/hooks/ + validateModel, sanitizeModel (~527 linhas removidas)' },
  { version: '1.36.68', feature: 'FASE 3 TIER 0 completo: useAPICache, usePrimaryTabLock, useFieldVersioning extraídos (~340 linhas removidas)' },
  { version: '1.36.67', feature: 'FASE 3: useThrottledBroadcast extraído para src/hooks/ (~50 linhas removidas)' },
  { version: '1.36.66', feature: 'FASE 3 Hooks TIER 0: useFullscreen, useSpacingControl, useFontSizeControl, useFeatureFlags extraídos para src/hooks/ (~245 linhas removidas)' },
  { version: '1.36.65', feature: 'Zustand Migration Wave 3: useProofManager migrado para useProofsStore.ts (~290 linhas removidas do App.tsx)' },
  { version: '1.36.64', feature: 'Zustand Migration Wave 3: useTopicManager migrado para useTopicsStore.ts (~180 linhas removidas do App.tsx)' },
  { version: '1.36.63', feature: 'Zustand Migration Wave 3: useModelLibrary migrado para useModelsStore.ts (core data, busca, filtros, formulário)' },
  { version: '1.36.62', feature: 'Zustand Migration Wave 2: useAIIntegration config/tokenMetrics migrado para useAIStore.ts (~80 linhas removidas)' },
  { version: '1.36.61', feature: 'Zustand Migration: useModalManager migrado para store global (src/stores/useUIStore.ts), devtools habilitado para debug' },
  { version: '1.36.60', feature: 'Fix Double Check factsComparison: correções agora são aplicadas na tabela (faltava caso para verifiedResult no performDoubleCheck)' },
  { version: '1.36.59', feature: 'Fix indicação "Modelo atual" na Config IA: agora exibe corretamente GPT-5.2/Grok 4.1 quando OpenAI ou Grok selecionado' },
  { version: '1.36.58', feature: 'Double Check para Confronto de Fatos: verifica completude, classificação e correção das alegações na tabela comparativa' },
  { version: '1.36.57', feature: 'Cache infinito para Revisar Sentença: persiste entre sessões (IndexedDB) e em export/import de projeto, badge de cache, botão regenerar' },
  { version: '1.36.56', feature: 'Double Check: novas operações Dispositivo e Revisar Sentença, dropdown de Thinking Level por provider/modelo (Claude/Gemini/OpenAI/Grok)' },
  { version: '1.36.55', feature: 'Fix feedback visual copiar em busca semântica: Jurisprudência e Legislação agora mostram Check verde' },
  { version: '1.36.54', feature: 'Feedback visual ao copiar tese na aba Jurisprudência: ícone Check verde por 2 segundos' },
  { version: '1.36.53', feature: 'Fix busca semântica jurisprudência: campo "text" vs "texto" - TypeScript usava nome português mas JSON usa inglês' },
  { version: '1.36.52', feature: 'Fix texto IRR vazio em busca semântica: fallback para fullText/texto quando tese/enunciado não disponível (embeddings)' },
  { version: '1.36.51', feature: 'Fix contraste Double Check no tema claro: badges "(em breve)" e aviso de custo legíveis em ambos os temas' },
  { version: '1.36.50', feature: 'Double Check de respostas da IA: verificação secundária para extração de tópicos (falsos positivos, omissões, categorização), provider/modelo configurável' },
  { version: '1.36.49', feature: 'Toggle "Log thinking" desabilitado para modelos sem reasoning (Grok e GPT-5.2 Instant)' },
  { version: '1.36.48', feature: 'Fix layout AIAssistantBase: aviso CNJ e seletor de escopo agora dentro da área de scroll' },
  { version: '1.36.47', feature: 'Fix "Invalid Date" no modal compartilhar biblioteca: API retornava created_at (snake_case), frontend esperava createdAt' },
  { version: '1.36.46', feature: 'Fix ESC no ConfigModal: não fecha se ModelGeneratorModal (Gerar a partir de exemplos) aberto, evita perda de scroll' },
  { version: '1.36.45', feature: 'Fix ESC no GlobalEditorModal: fecha sub-modais (Jurisprudência/Assistente IA/Confronto) primeiro, reseta estados ao abrir' },
  { version: '1.36.44', feature: 'Deletar 16 arquivos de testes/hooks duplicados: 222 testes inúteis removidos (testavam código que não roda em produção)' },
  { version: '1.36.43', feature: 'Fix test failure: guard scrollIntoView em TopicCurationModal (JSDOM não implementa)' },
  { version: '1.36.42', feature: 'Build inclui tsc --noEmit: verificação de tipos antes do deploy (previne erros como ReferenceError)' },
  { version: '1.36.41', feature: 'Fix ReferenceError: usar documentServices.extractTextFromPDFWithMode (prefixo faltando)' },
  { version: '1.36.40', feature: 'Fix NER provas: usar extractTextFromPDFWithMode com modo selecionado (PDF.js ou Tesseract) ao invés de extractTextFromPDFPure' },
  { version: '1.36.39', feature: 'Fix NER em provas: "Detectar Nomes" agora extrai texto da PROVA (não da petição) - removido fallback incorreto' },
  { version: '1.36.38', feature: 'Aviso visual Grok na aba Provas: alerta laranja "Grok não suporta PDF binário" quando PDF sem texto extraído (similar ao aviso roxo de anonimização)' },
  { version: '1.36.37', feature: 'Fix bloqueio PDF com Grok: botão "Usar PDF" desabilitado no ProofCard, fallback para PDF completo bloqueado quando extração falha (anonimização/Grok), mensagem "extração obrigatória" em vermelho' },
  { version: '1.36.36', feature: 'Bloquear PDF Puro quando Grok selecionado: opção desabilitada nos seletores (Uploads e Provas), Claude Vision liberado' },
  { version: '1.36.35', feature: 'Fix estimativa de custo: mostrar modelo correto para OpenAI/Grok no TopicCurationModal (antes mostrava Claude)' },
  { version: '1.36.34', feature: 'Tesseract OCR: mais logs de diagnóstico (canvas render, OCR batch, cada página) para identificar gargalo' },
  { version: '1.36.33', feature: 'Tesseract OCR fix: primeiro worker baixa modelo sozinho (cacheia), depois cria demais em paralelo + logs de diagnóstico' },
  { version: '1.36.32', feature: 'Fix exclusão de prova: usar handleDeleteProof do hook (tipagem correta)' },
  { version: '1.36.31', feature: 'Fix exclusão de prova: String() na comparação de IDs (type mismatch number/string)' },
  { version: '1.36.30', feature: 'Fix botão excluir prova: race condition isOpen && proofToDelete no DeleteProofModal' },
  { version: '1.36.29', feature: 'Suporte PDF para OpenAI (type: file) + aviso Grok não suporta PDF binário nas abas Upload e Provas' },
  { version: '1.36.28', feature: 'Fix análise de provas: isPdf não setado na criação + verificação robusta com type === pdf' },
  { version: '1.36.27', feature: 'Fix background transparente no AIAssistantBase: adicionado overflow-y-auto flex-1 min-h-0 ao content' },
  { version: '1.36.26', feature: 'Fix stale cache Confronto ao trocar tópico: useEffect limpa resultado quando editingTopic muda' },
  { version: '1.36.25', feature: 'Fix contraste badges Confronto de Fatos no tema claro: cores -600 para tema claro, -400 para tema escuro' },
  { version: '1.36.24', feature: 'Fix cache Confronto de Fatos no editor individual: handleOpenFactsComparisonIndividual recupera cache do IndexedDB antes de abrir modal' },
  { version: '1.36.23', feature: 'Fix scroll BaseModal: min-h-0 no content div permite flexbox shrink e scroll interno funcionar corretamente' },
  { version: '1.36.22', feature: 'Fix Confronto de Fatos: fallback para PDF binário quando texto não extraído + scroll no BaseModal (max-h-[90vh] flex flex-col)' },
  { version: '1.36.21', feature: 'Refatorar FactsComparisonModal para usar BaseModal (padrão do app) + Botão Confronto no editor individual de tópicos + diretriz #6 no CLAUDE.md sobre uso obrigatório de BaseModal' },
  { version: '1.36.20', feature: 'Confronto de Fatos: botão na toolbar do editor abre modal para comparar alegações Petição vs Contestação vs Impugnação por tópico, tabela com fatos controversos/incontroversos, cache IndexedDB com TTL infinito, export/import no projeto' },
  { version: '1.36.19', feature: 'Fix UI edição prompts rápidos: campo de texto e onChange usavam name em vez de label (bug da migração TS)' },
  { version: '1.36.18', feature: 'Fix botões prompt rápido vazios (qp.name→qp.label) + nota sobre limitação Grok 4.x reasoning na API' },
  { version: '1.36.17', feature: 'Log thinking no console para Grok: toggle "Log thinking" agora funciona com Grok 4.1 Fast Thinking' },
  { version: '1.36.16', feature: 'Fix erro 502 Grok: formatar x-grok-conv-id como UUID4 válido (com hífens)' },
  { version: '1.36.15', feature: 'Fix espaçamento do checkbox "Log thinking no console" no Config IA Modal (mt-4)' },
  { version: '1.36.14', feature: 'Grok cache hit rate: header x-grok-conv-id baseado na API key para manter sessão de cache, log de cached tokens no servidor' },
  { version: '1.36.13', feature: 'UX: Auto-scroll e focus no MergeConfirm do TopicCurationModal - ao clicar "Mesclar", scroll suave para o formulário + cursor no campo de título' },
  { version: '1.36.12', feature: 'OpenAI/Grok na estimativa de custo: seção "Uso de Tokens" mostra 6 modelos (Claude Sonnet/Opus, Gemini Pro/Flash, OpenAI GPT-5.2, Grok 4.1) + "Limites por API" com 4 providers (grid responsivo)' },
  { version: '1.36.11', feature: 'UX: Indicador visual claro de thinking no Grok - badges "Thinking Embutido" (roxo) e "Sem Thinking" (âmbar) na seção Pensamento Prolongado' },
  { version: '1.36.10', feature: 'feat(multi-provider): Integração OpenAI GPT-5.2 + xAI Grok 4.1 - 4 providers (Claude, Gemini, OpenAI, Grok), reasoning configurável, Grok 96% mais barato que Claude' },
  { version: '1.36.9', feature: 'Fix bullet list no Quill: override ::before para data-list="bullet" (CSS do CDN não tem regra para bullets em <ol>)' },
  { version: '1.36.8', feature: 'Fix listas no Quill: list-style-type: none para evitar duplicação (Quill usa ::before para marcadores)' },
  { version: '1.36.7', feature: 'Fix lista bolinha: CSS respeita data-list, export converte <ol> bullet para <ul>, blockquote sem border-left' },
  { version: '1.36.6', feature: 'Fix exportação: listas bullet (data-list), indent (ql-indent-*), blockquote - DOMPurify agora permite atributos necessários' },
  { version: '1.36.5', feature: 'Fix exportação minuta: converter classes ql-align-* do Quill para inline styles (Google Docs ignora classes CSS)' },
  { version: '1.36.4', feature: 'Fix exportação minuta: preserva alinhamento do usuário (center, right) - remove align deprecated, corrige bug que sobrescrevia text-align' },
  { version: '1.36.3', feature: 'Fix exportação minuta: atributo align="center/justify" para Google Docs (style inline não era suficiente)' },
  { version: '1.36.2', feature: 'Fix exportação minuta: estilos inline para Google Docs (alinhamento centralizado/justificado preservado) - EXPORT_STYLES em src/constants/export-styles.ts' },
  { version: '1.36.1', feature: 'Fix race condition ao salvar modelo: dados passados diretamente para saveModel (evita erro "Título e conteúdo são obrigatórios" causado por state assíncrono)' },
  { version: '1.36.0', feature: '🎉 TypeScript strict mode COMPLETO - Zero errors (tsc --noEmit passa), migração de ~930 erros concluída, tipos alinhados, null safety' },
  { version: '1.35.89', feature: 'TypeScript FASE 8.7: Tipagem de event handlers (KeyboardEvent para ESC handlers, StorageEvent para multi-tab sync, CustomEvent para spacing/fontSize) - erros TS7006: 930→711' },
  { version: '1.35.88', feature: 'TypeScript Migration FASE 8.7: Tipagem de callAI/callLLM/callGemini, buildApiRequest, convertToGeminiFormat, extractTokenMetrics, extractResponseText + propriedades adicionais em AICallOptions + AIMessageContent import' },
  { version: '1.35.87', feature: 'TypeScript Migration FASE 8.7 (parcial): Tipagem completa de AIModelService, EmbeddingsService, JurisEmbeddingsService, EmbeddingsCDNService + callbacks do useAIIntegration (930→775 erros TS7006)' },
  { version: '1.35.86', feature: 'TypeScript Migration FASE 8.6: Tipagem de 84 useRef<T> - timers (ReturnType<typeof setTimeout>), DOM refs (HTMLDivElement, HTMLInputElement), Quill instances, callbacks, caches (Map<K,V>)' },
  { version: '1.35.85', feature: 'TypeScript Migration FASE 8.1-8.5: +20 tipos em src/types/index.ts (TextPreviewState, ToastState, SlashMenuState, ProgressState, PastedText, ChatMessage, Precedente, Artigo, etc.) + useState com objetos/arrays/null tipados' },
  { version: '1.35.80', feature: 'TypeScript Migration: prompts migrados (system.ts, ai-prompts.ts, meta-prompts.ts) + barrel exports em src/prompts/index.ts' },
  { version: '1.35.79', feature: 'TypeScript Migration FASE 5: App.jsx → App.tsx (~35000 linhas) - build OK, 503 testes passando' },
  { version: '1.35.78', feature: 'TypeScript Migration FASE 1-4: 11 hooks migrados (useModalManager, useFieldVersioning, useLocalStorage, useModelPreview, useTopicManager, useModelLibrary, useAIIntegration, useProofManager, useAuthMagicLink, useSyncManager, useCloudSync) + src/types/index.ts com 40+ tipos core' },
  { version: '1.35.77', feature: 'Gerar Estilo de Redação a partir de exemplos: botão "Gerar a partir de exemplos" no campo Estilo de Redação Personalizado - IA analisa sentenças do juiz e extrai TOM/VOCABULÁRIO/RITMO (buildStyleMetaPrompt)' },
  { version: '1.35.76', feature: 'Estilo Personalizado Substitutivo: AI_INSTRUCTIONS refatorado em CORE/STYLE/SAFETY - customPrompt do juiz SUBSTITUI (não complementa) o estilo default, evitando conflitos como "Use latinismos" vs "Evite latinismos"' },
  { version: '1.35.75', feature: 'UX: Feedback inline no botão Testar API Key - mostra ✓ (verde) ou ✗ (vermelho) por 2s ao invés de toast popup' },
  { version: '1.35.74', feature: 'Config IA Local exportada no projeto + apiKeys excluída do export (segurança): 8 campos movidos de localStorage para aiSettings, migração automática, preserva apiKeys do usuário no import' },
  { version: '1.35.73', feature: 'Fix header opaco no ModelGeneratorModal: conteúdo não vaza por baixo ao fazer scroll (theme-bg-primary 100% + backdrop-blur)' },
  { version: '1.35.72', feature: 'ModelGeneratorModal segue padrão BaseModal: ESC handler com stopPropagation (fecha modal correto), scroll lock' },
  { version: '1.35.71', feature: 'Fix z-index ModelGeneratorModal (z-100 > CSS.modalOverlay z-90) - modal abre acima do ConfigModal' },
  { version: '1.35.70', feature: '(tentativa anterior z-70 insuficiente)' },
  { version: '1.35.69', feature: 'Gerador Automático de Prompts: juiz cola exemplos → IA gera prompt profissional que reproduz seu estilo (meta-prompts.ts, ModelGeneratorModal.tsx)' },
  { version: '1.35.68', feature: 'Fix: botão X posicionado corretamente no TextPreviewModal (flex no header) e ModelPreviewModal (classe padronizada para tema claro)' },
  { version: '1.35.67', feature: 'UX: 4 modais migrados para padrão BaseModal (TextPreviewModal, ModelPreviewModal, Download de Dados, Download de Embeddings) - ESC handler, scroll lock, glassmorphism' },
  { version: '1.35.66', feature: 'UX: Modal "Excluir Toda Legislação" migrado para BaseModal (ESC handler, botão X, scroll lock, glassmorphism)' },
  { version: '1.35.65', feature: 'UX: VoiceButton movido para linha dos botões Jurisprudência/Assistente IA no editor global (FieldEditor prop hideVoiceButton)' },
  { version: '1.35.64', feature: 'UX: JurisprudenciaModal, AIAssistantBaseLegacy e ConfigModal seguem padrão BaseModal (ESC handler, botão X, scroll lock, glassmorphism)' },
  { version: '1.35.63', feature: 'UX: BaseModal bloqueia scroll do body quando aberto (evita scroll da página por baixo)' },
  { version: '1.35.62', feature: 'VoiceButton corrigido: removido de título/keywords, adicionado no editor global (FieldEditor) e assistente IA de modelos (AIAssistantBaseLegacy)' },
  { version: '1.35.61', feature: 'VoiceButton expandido: editor de modelos (QuillModelEditor) e Quick Edit (ModelPreviewModal)' },
  { version: '1.35.60', feature: 'Voice-to-Text Preview Flutuante: tooltip mostra texto em tempo real enquanto fala, só insere no editor quando resultado é final (feedback instantâneo)' },
  { version: '1.35.59', feature: 'Voice-to-Text: ditado por voz via Web Speech API nos editores de decisão, instruções para IA e chat do assistente (useVoiceToText hook + VoiceButton componente)' },
  { version: '1.35.58', feature: 'Worker Error Handling: onerror handler para rejeitar promises pendentes, timeout de 60s nas chamadas, método cleanup() para reset do AIModelService' },
  { version: '1.35.57', feature: 'UX: botão Sair movido para a mesma linha do botão Projeto (layout mais compacto)' },
  { version: '1.35.56', feature: 'Fix: botão Sair volta para o header (logout geral do sistema), apenas indicador + email ficam na aba Modelos' },
  { version: '1.35.55', feature: 'Bloco de sync de modelos (indicador + email) movido do header para a aba Modelos' },
  { version: '1.35.54', feature: 'Foto do perfil Google exibida no status de conexão Drive (ao lado do email)' },
  { version: '1.35.53', feature: 'UX: ícone Cloud preenchido (sólido) quando conectado ao Google Drive - contraste visual claro' },
  { version: '1.35.52', feature: 'UI consolidada: botão "Limpar Projeto" também incorporado ao dropdown (único botão "Projeto" no header)' },
  { version: '1.35.51', feature: 'UI consolidada: botões Salvar/Carregar Projeto movidos para dropdown "Projeto" (seções Google Drive + Local em um único lugar)' },
  { version: '1.35.50', feature: 'Google Drive migrado para TypeScript: useGoogleDrive.ts e GoogleDriveButton.tsx com interfaces tipadas (convenção de novos arquivos)' },
  { version: '1.35.49', feature: 'UX Polish: remover opção de permissão no compartilhamento Drive (sempre cópia), texto "Modelos sincronizados" mais claro, fix contraste tags categoria no tema claro' },
  { version: '1.35.48', feature: 'Google Drive: fix compartilhamento - arquivos compartilhados agora aparecem (sharedWithMe), botão para remover acesso no modal de permissões' },
  { version: '1.35.47', feature: 'Google Drive: arquivos salvos na pasta "Sentencify" (criada automaticamente) para melhor organização' },
  { version: '1.35.46', feature: 'Google Drive: filtrar por appProperties - mostra apenas arquivos criados pelo Sentencify (ignora compartilhamentos externos)' },
  { version: '1.35.45', feature: 'Google Drive compartilhamento corrigido: escopo drive.readonly permite ver arquivos de outros, badges "De: fulano" e "Compartilhado", modal de permissões' },
  { version: '1.35.44', feature: 'Header COOP (Cross-Origin-Opener-Policy) no servidor: elimina warning do Google OAuth popup no console' },
  { version: '1.35.43', feature: 'Compartilhar arquivos do Google Drive: botão para enviar por email com permissão de visualização ou edição' },
  { version: '1.35.42', feature: 'Fix erro React #31: notificações do Google Drive agora suportam objeto {type, message} (sucesso em verde, erro em vermelho)' },
  { version: '1.35.41', feature: 'Refatoração: exportProject e importProject usam buildProjectJson/importProjectFromJson (elimina ~200 linhas duplicadas)' },
  { version: '1.35.40', feature: 'Google Drive: salvar e carregar projetos na nuvem pessoal do usuário (OAuth2, sem custo adicional, até 750GB/dia)' },
  { version: '1.35.39', feature: 'Calibra estimativa de custo: constantes de tokens ajustadas com dados reais (BASE_CONTEXT 8K→3.5K, OUTPUT 3.5K→1.8K, GEMINI_THINKING ~50%)' },
  { version: '1.35.38', feature: 'Fix lag drag no modal: DragOverlay via createPortal(body) escapa CSS do modal, CSS.Translate para melhor performance, TopicCardVisual componente visual puro' },
  { version: '1.35.37', feature: 'Estimativa de custo melhorada: considera thinking tokens (Claude/Gemini), batch size (topicsPerRequest), tooltip com breakdown detalhado' },
  { version: '1.35.36', feature: 'Fix drag lag: remover willChange dinâmico (causava repaints contínuos), distance 8px (igual App.jsx)' },
  { version: '1.35.35', feature: 'Otimização drag FPS: React.memo no TopicPreviewCard, callbacks com setter funcional (sem dependências)' },
  { version: '1.35.34', feature: 'TopicCurationModal UX: modal não pode ser fechado (sem X, ESC, backdrop), largura 80vw, undo restaura no índice correto, custo exibe modelo (ex: R$ 1.04 Gemini 3 Flash)' },
  { version: '1.35.33', feature: 'TypeScript incremental: TopicCurationModal.tsx como primeiro arquivo .tsx (tsconfig.json com allowJs: true)' },
  { version: '1.35.32', feature: 'Fix z-index TopicCurationModal: aparece acima do AnalysisModal (z-[100] vs z-[90])' },
  { version: '1.35.31', feature: 'Testes TopicCurationModal (49 testes): renderização, callbacks, edição inline, exclusão, mesclagem, separação, adição, estimativa de custo, tópicos especiais' },
  { version: '1.35.30', feature: 'Modal de Curadoria de Tópicos: revisar, reordenar, mesclar, separar e apagar tópicos ANTES de gerar mini-relatórios (economia de tokens, estimativa de custo R$/tempo)' },
  { version: '1.35.29', feature: 'Fix meta-comentários de revisão nos mini-relatórios: prompt proíbe textos como "Revisei esta resposta..." + pós-processamento remove automaticamente (com log no console)' },
  { version: '1.35.28', feature: 'Fix testes E2E no CI: useAuth retorna early se localStorage tem sessão (evita timeout esperando servidor)' },
  { version: '1.35.27', feature: 'Testes de prompts agora usam AI_PROMPTS real (corrige MOCK_PROMPTS perigoso que não detectava mudanças)' },
  { version: '1.35.26', feature: 'Prompts de IA (AI_INSTRUCTIONS, AI_PROMPTS) movidos para src/prompts/ (~900 linhas extraídas do App.jsx)' },
  { version: '1.35.25', feature: 'CHANGELOG movido para src/constants/changelog.js (reduz clutter no App.jsx)' },
  { version: '1.35.24', feature: 'Fix B8b: sync remove modelos de owners sem acesso ativo (sharedLibraries filtra modelos locais compartilhados)' },
  { version: '1.35.23', feature: 'Fix B8: remover share via UI limpa modelos da biblioteca + A7a: trackChangeBatch para importação em lote eficiente' },
  { version: '1.35.22', feature: 'Fix duplicar modelo compartilhado (agora cria cópia própria) + tratamento de conflitos de sync (pull após conflito, model_deleted, no_permission)' },
  { version: '1.35.21', feature: 'Fix modelos compartilhados sumiam após sync incremental: preservar locais quando servidor não retorna compartilhados' },
  { version: '1.35.20', feature: 'Fix progresso de download: usa tamanhos estimados como fallback quando Content-Length não disponível (streaming proxy)' },
  { version: '1.35.19', feature: 'Fix modelos compartilhados não apareciam após aceitar: comparar accepted_at com lastSyncAt para detectar shares recém-aceitos' },
  { version: '1.35.18', feature: 'Log de diagnóstico para rate limiting: IP, email e User-Agent em cada request de magic link' },
  { version: '1.35.17', feature: 'Fix rate limiter: trust proxy para Cloudflare/Render (antes todos IPs eram iguais)' },
  { version: '1.35.16', feature: 'Email com domínio verificado: sentencify.ia.br em vez de resend.dev' },
  { version: '1.35.15', feature: 'Fix E2E tests: remover setupAuth órfão (fixture já faz autenticação)' },
  { version: '1.35.14', feature: 'Labels explícitos para PDFs binários: antes de cada PDF, adiciona texto identificador para IA saber qual documento é qual' },
  { version: '1.35.13', feature: 'Rate limiting: proteção contra abuso (auth 10/15min, IA 30/min, geral 100/min)' },
  { version: '1.35.12', feature: 'Sentry error tracking: captura erros em produção (frontend + backend), alertas por email, stack traces completos' },
  { version: '1.35.11', feature: 'Fix sync: pull-then-push evita conflitos, retry com limit para conflitos de versão, shared filter por lastSyncAt, validação email no accept' },
  { version: '1.35.10', feature: 'Fix lag REAL: estado local bufferizado em ModelFormModal e AIRegenerationSection - digitação não propaga para LegalDecisionEditor (Análise Gemini)' },
  { version: '1.35.9', feature: 'Fix lag em TODOS inputs: todos os 11 setters de useAIIntegration convertidos para useCallback + useCloudSync.return memoizado com useMemo' },
  { version: '1.35.8', feature: 'Fix lag final: findSuggestions e refineWithAI agora usam useCallback (evita re-criação a cada render que quebrava React.memo)' },
  { version: '1.35.7', feature: 'Fix lag residual no "regenerar com IA": setRelatorioInstruction/setDispositivoInstruction agora usam useCallback (referência estável)' },
  { version: '1.35.6', feature: 'Fix lag no campo "regenerar com IA": removidas arrow functions inline em onInstructionChange (passando função direta)' },
  { version: '1.35.5', feature: 'Fix erro "Rendered more hooks" no ModelFormModal: hooks useCallback movidos para antes do return condicional' },
  { version: '1.35.4', feature: 'Fix lag causado por dependência circular no Cloud Sync: libraryModels nas deps do useEffect causava loop infinito de re-renders ao digitar' },
  { version: '1.35.3', feature: 'Fix lag de escrita nos editores: debounce 150ms no onChange/sanitização do Quill, memoização de getCategories, primitivos em isIndividualDirty' },
  { version: '1.35.2', feature: 'Fix exclusão em massa: deleteAllModels() agora rastreia cada modelo para sync; delete salva apenas id (evita QuotaExceededError no localStorage)' },
  { version: '1.35.1', feature: 'Compartilhamento por email: convite direto, edição colaborativa (edit permite editar/deletar originais), fix sync modelos deletados, fix typing lag' },
  { version: '1.35.0', feature: 'Compartilhamento de biblioteca: gerar link para compartilhar modelos (view/edit), badge de proprietário, filtro Meus/Compartilhados' },
  { version: '1.34.9', feature: 'Fix validação: aceita null em category/keywords (antes rejeitava modelos com campos opcionais null)' },
  { version: '1.34.8', feature: 'Fix cache IndexedDB: atualizado com modelos validados + log de modelos rejeitados para debug' },
  { version: '1.34.7', feature: 'Fix sync: salva IMEDIATAMENTE no IndexedDB após merge (debounce de 1500ms causava perda de dados)' },
  { version: '1.34.6', feature: 'Sync inteligente: compara contagem local vs servidor, força full sync se diferente' },
  { version: '1.34.5', feature: 'Fix race condition: merge de sync agora espera IndexedDB carregar (evita perda de modelos)' },
  { version: '1.34.4', feature: 'Admin Panel: interface /admin para gerenciar emails autorizados via Magic Link (protegida por senha)' },
  { version: '1.34.3', feature: 'Cloud Sync Full Sync + UPSERT: navegador novo baixa todos modelos, INSERT OR REPLACE evita conflitos' },
  { version: '1.34.2', feature: 'Cloud Sync Pull Paginado: 50 modelos por request evita crash de memória' },
  { version: '1.34.1', feature: 'Cloud Sync Pull Merge: modelos recebidos do servidor são mesclados com IndexedDB local' },
  { version: '1.34.0', feature: 'Cloud Sync: Magic Link Authentication + SQLite Sync - modelos salvos na nuvem (Render Persistent Disk)' },
  { version: '1.33.63', feature: 'Testes E2E expandidos (88 testes): auth, pdf-upload, generation, export, search' },
  { version: '1.33.62', feature: 'Modal "Sessão Anterior Encontrada" não pode ser fechado (ESC, X, click fora) - usuário deve escolher' },
  { version: '1.33.61', feature: 'Auto-download de dados: legislação e jurisprudência baixados automaticamente do GitHub Releases (~5 MB, download único)' },
  { version: '1.33.60', feature: 'Otimização drag: collision detection O(n) com Set pré-computado (antes O(n²) com find)' },
  { version: '1.33.59', feature: 'Fix drag feedback visual: collision detection customizado ignora RELATÓRIO/DISPOSITIVO' },
  { version: '1.33.58', feature: 'dnd-kit para drag and drop de tópicos - suporte a wheel scroll durante arraste' },
  { version: '1.33.57', feature: 'Modal estilizado para confirmação de logout (substituir window.confirm nativo)' },
  { version: '1.33.56', feature: 'Reduzir espaçamento entre cards no modo lista (space-y-1, itemHeight 90)' },
  { version: '1.33.55', feature: 'Fix borda superior cortada no hover do modo lista - remover card-hover-lift (translateY invadia card acima)' },
  { version: '1.33.54', feature: 'Fix borda sumindo no hover do modo lista (ModelCard) - border-2 para consistência com cards' },
  { version: '1.33.53', feature: 'Otimizar hover elevation - GPU acceleration (will-change, translateZ, transition específica)' },
  { version: '1.33.52', feature: 'Fix mensagens hardcoded no bulk upload - agora mostra valor real de parallelRequests' },
  { version: '1.33.51', feature: 'Modal changelog migrado para BaseModal (ESC para fechar + glassmorphism)' },
  { version: '1.33.50', feature: 'Micro-interações visuais: cards com hover elevação, badges fade-in, estrela favorito colorida, empty states pulsando, drag&drop suave, focus rings, spinner neon no app loading' },
  { version: '1.33.49', feature: 'Spinner Neon + Ripple no AnalysisModal (anéis girando com ondas pulsantes)' },
  { version: '1.33.48', feature: 'ESC handler centralizado no BaseModal (18 modais beneficiados)' },
  { version: '1.33.47', feature: 'Glassmorphism + ESC em 7 modais (ExtractModel, AIAssistant, Analysis, Dispositivo, Similarity, Config)' },
  { version: '1.33.46', feature: 'Aplicar estilo Glassmorphism ao BulkUploadModal (consistência visual)' },
  { version: '1.33.45', feature: 'Migrar ProofAnalysisModal e LinkProofModal para BaseModal (padronização UI)' },
  { version: '1.33.44', feature: 'Fix título e botão X dos modais no tema claro' },
  { version: '1.33.43', feature: 'Fix modais: tema claro respeitado, transparência adequada, glow adaptativo' },
  { version: '1.33.42', feature: 'Modais com estilo Glassmorphism: blur, gradientes, ícones em círculos, botão X, animação suave' },
  { version: '1.33.41', feature: 'Autenticação simples: tela de login, senha hasheada (SHA-256), botão Sair no header' },
  { version: '1.33.40', feature: 'Validação de PDFs (33 testes): magic bytes, tamanho, tipo, estimativa de tempo de processamento' },
  { version: '1.33.39', feature: 'Testes de regressão de prompts (21 testes snapshot): validação de estrutura, Art. 337 CPC, ordem do mérito' },
  { version: '1.33.38', feature: 'Testes de integração (71 testes): topicOrdering, analyzeProof, generateSentence + utilitários extraídos em src/utils' },
  { version: '1.33.37', feature: 'Comentários padronizados: 9 seções com bordas ═══ e descrições (IMPORTS, UTILITÁRIOS, HOOKS, UI, MODAIS, QUILL, AI_PROMPTS, LEGALDECISIONEDITOR, ERROR BOUNDARY)' },
  { version: '1.33.36', feature: 'Índice/mapa estruturado no topo do arquivo: navegação rápida para LLMs, 9 seções mapeadas, fluxos críticos documentados' },
  { version: '1.33.35', feature: 'Ordenação v3: numeração única (6a-6f), sem referências cruzadas, explicações contextuais mantidas' },
  { version: '1.33.34', feature: 'Ordenação v2: 7 grupos (tramitação, preliminares, prejudiciais, mérito, finais) + ordem lógica do mérito (CAUSA > OBRIGAÇÃO > EFEITO)' },
  { version: '1.33.33', feature: 'Ordenação de preliminares conforme Art. 337 CPC (13 incisos na ordem legal)' },
  { version: '1.33.32', feature: 'Fix embeddings 502: streaming com Readable.fromWeb() evita OOM no Render free tier (512MB RAM)' },
  { version: '1.33.31', feature: 'Migração para Render: sem limite de payload (100MB vs 4.5MB Vercel), heartbeat keepalive, timeout 100min' },
  { version: '1.33.30', feature: 'Testes sanitizeHTML expandidos (39 testes XSS) - total 285 testes (261 unit + 24 E2E)' },
  { version: '1.33.29', feature: 'Testes E2E expandidos (24 testes) - total 267 testes (243 unit + 24 E2E)' },
  { version: '1.33.28', feature: 'Testes useTopicManager (42 testes) - total 243 testes unitários' },
  { version: '1.33.27', feature: 'Reverter useModalManager para App.jsx (consistência: todos hooks no mesmo padrão)' },
  { version: '1.33.26', feature: 'Refatorar useModalManager para arquivo separado (melhor testabilidade)' },
  { version: '1.33.25', feature: 'Fix setState durante render: contextualInsertFn como ref em useModelPreview' },
  { version: '1.33.24', feature: 'Fix HTML nesting warning: spinner div→span no GlobalEditorModal' },
  { version: '1.33.23', feature: 'Fix infinite loop: ref para handleInsertModel em GlobalEditorModal' },
  { version: '1.33.22', feature: 'Fix infinite loop: useMemo em useFieldVersioning e useModelPreview' },
  { version: '1.33.21', feature: 'Fix botão limpar formatação (usa format(key,false) em vez de removeFormat)' },
  { version: '1.33.20', feature: 'Fix botão limpar formatação + toggle semântico por padrão + badge similaridade sempre visível' },
  { version: '1.33.19', feature: 'Botão limpar formatação no editor + toggle 🧠/🔤 semântico na busca manual de modelos' },
  { version: '1.33.18', feature: 'Badge % similaridade em jurisprudência e modelos sugeridos (modo semântico)' },
  { version: '1.33.17', feature: 'Fix modal jurisprudência: sincronizar toggle com config IA Local ao abrir' },
  { version: '1.33.16', feature: 'Modal jurisprudência: badge 🤖 IA Local + toggle 🧠/🔤 semântico/textual' },
  { version: '1.33.15', feature: 'Fix batchSize hardcoded em mini-relatórios/subtópicos + contraste "Erro 429" no tema escuro' },
  { version: '1.33.14', feature: 'Fix NER: indexOf case-insensitive, dedup inclui entityType, fallback ORG limitado a 4 palavras + normaliza espaços' },
  { version: '1.33.13', feature: 'NER healing: subtokens órfãos (##edo) unidos ao prefixo (Mac→Macedo) + fallback regex para ORG (V2 LTDA)' },
  { version: '1.33.12', feature: 'Fix contraste do aviso de erro 429 no tema claro' },
  { version: '1.33.11', feature: 'Requisições paralelas configuráveis: escolha 3-20 em Config IA, com explicativo de limites por API/tier' },
  { version: '1.33.10', feature: 'Tooltip no SlashCommand mostra modelo completo (não truncado)' },
  { version: '1.33.9', feature: 'Fix contraste do badge de similaridade no SlashCommand (tema claro)' },
  { version: '1.33.8', feature: 'SlashCommand melhorado: posicionamento viewport-aware, tooltip preview, busca semântica, hover corrigido nos toggles 🧠' },
  { version: '1.33.7', feature: 'Feedback visual ao duplicar modelo: toast "Duplicando..." durante geração de embedding' },
  { version: '1.33.6', feature: 'Layout 1 card por linha em toda aba Modelos (busca textual + inicial)' },
  { version: '1.33.5', feature: 'Layout 1 card por linha na busca semântica de modelos' },
  { version: '1.33.4', feature: 'Unificar UI busca semântica de modelos: usar ModelCard com editar/duplicar/excluir, respeitar modo cards/lista, badge de similaridade' },
  { version: '1.33.3', feature: 'Feedback visual "Salvando..." no SimilarityWarningModal durante geração de embedding' },
  { version: '1.33.2', feature: 'Remover logs de AI/Search em produção (apenas em DEV)' },
  { version: '1.33.1', feature: 'Fix CORS: proxy serverless para download embeddings, UI simplificada (remove import manual), z-index modal corrigido' },
  { version: '1.33.0', feature: 'Auto-download de embeddings via CDN: legislação e jurisprudência baixados automaticamente do GitHub Releases (~250MB)' },
  { version: '1.32.42', feature: 'Migrar Tailwind CDN para PostCSS: build-time compilation, remove warning de produção, CSS otimizado' },
  { version: '1.32.41', feature: 'Suporte a deploy Vercel: serverless functions (/api/claude, /api/gemini), API_BASE dinâmico (local vs prod)' },
  { version: '1.32.40', feature: 'Toggle para ativar/desativar logs de thinking no console (Config IA > Log thinking no console)' },
  { version: '1.32.39', feature: 'Log de thinking no console do browser: Claude (extended thinking) e Gemini 3 (includeThoughts) para debug e análise' },
  { version: '1.32.38', feature: 'Gemini thinking buffer: auto-aumenta maxOutputTokens baseado no thinking_level (high +16K, medium +8K, low +4K, minimal +2K)' },
  { version: '1.32.37', feature: 'Fix Gemini 3 Pro: validar thinking_level (Pro só suporta low/high, minimal/medium convertidos para low)' },
  { version: '1.32.36', feature: 'Removido Gemini 2.5: apenas Gemini 3 Flash/Pro disponíveis, UI simplificada (thinking_level apenas)' },
  { version: '1.32.35', feature: 'Fix Gemini thinking: extração de texto agora busca part sem thought=true (antes pegava parts[0] que era thinking)' },
  { version: '1.32.34', feature: 'Fix reorderTopicsViaLLM: regex mais robusto (suporta markdown code blocks, newlines no JSON)' },
  { version: '1.32.33', feature: 'Auto-timeout 5 min para thinking budgets >= 40K + warning "respostas podem demorar mais"' },
  { version: '1.32.32', feature: 'Budget thinking dinâmico por modelo Claude: Sonnet até 62K, Opus até 30K + warning para budgets >= 40K (risco timeout)' },
  { version: '1.32.31', feature: 'UI Gemini 2.5 Pro: toggle mostra "Mínimo" + badge "1024 tokens" quando thinking "desativado" (API não permite desligar)' },
  { version: '1.32.30', feature: 'Fix thinking config: Gemini 2.5 Flash agora desativa thinking com budget 0 (antes usava dinâmico), 2.5 Pro usa mínimo' },
  { version: '1.32.29', feature: 'Fix crítico Gemini: useInstructions agora envia AI_INSTRUCTIONS como systemInstruction (13 funcionalidades corrigidas)' },
  { version: '1.32.28', feature: 'Chat assistente: verificação obrigatória - LLM deve listar informações pendentes ANTES de redigir' },
  { version: '1.32.27', feature: 'Chat assistente: instrução de perguntas fortalecida - "prefira perguntar a presumir"' },
  { version: '1.32.26', feature: 'Chat assistente: maxTokens 16000 + log finishReason no servidor Gemini' },
  { version: '1.32.25', feature: 'Fix reorderTopicsViaLLM: regex robusto + maxTokens 4000 (evita truncamento com Gemini 3)' },
  { version: '1.32.24', feature: 'Modal de changelog ao clicar na versão' },
  { version: '1.32.23', feature: 'Títulos de tópicos com causa de pedir nuclear: prompt ajustado para gerar títulos como "RESCISÃO INDIRETA - ASSÉDIO MORAL"' },
  { version: '1.32.22', feature: 'Sugestões de modelos usando apenas título: embedding da query usa só topic.title' },
  { version: '1.32.21', feature: 'Filtros antes do limit: filtros de tipo/tribunal aplicados ANTES de limitar em 30 resultados' },
  { version: '1.32.20', feature: 'Fix case sensitivity E5: queries convertidas para toLowerCase()' },
  { version: '1.32.19', feature: 'Fix busca semântica no modal de jurisprudência' },
  { version: '1.32.18', feature: 'Busca semântica de jurisprudência nos editores' },
  { version: '1.32.17', feature: 'NER sob demanda: modelo carrega só ao clicar "Detectar Nomes"' },
  { version: '1.32.16', feature: 'Botões responsivos na aba Tópicos' },
  { version: '1.32.15', feature: 'Tesseract alta qualidade: SCALE 4.0 + PSM 6' },
  { version: '1.32.14', feature: 'Fix Tesseract em Provas' },
  { version: '1.32.13', feature: 'Permitir Tesseract com anonimização' },
  { version: '1.32.12', feature: 'Fix mergeOrgLoc: aceita ORG+ORG curto' },
  { version: '1.32.11', feature: 'Botão Manual do Usuário (📖) no header' },
  { version: '1.32.10', feature: 'NER fusão ORG+LOC' },
  { version: '1.32.09', feature: 'Fix NER modelo: BERT completo' },
  { version: '1.32.08', feature: 'IA Local via Web Worker' },
  { version: '1.32.07', feature: 'Fix NER separação de nomes' },
  { version: '1.32.06', feature: 'Auto-inicialização modelos NER/E5' },
  { version: '1.32.00', feature: 'IA Local Refatoração: Web Worker, modelos HuggingFace' },
  { version: '1.31.04', feature: 'IA Local Otimização: SIMD/threads/WebGPU' },
  { version: '1.31.00', feature: 'Tesseract.js OCR Offline' },
  { version: '1.30.00', feature: 'Gemini Vision OCR' },
  { version: '1.29.00', feature: 'NER incluir ORG (empresas)' },
  { version: '1.28.02', feature: 'Sugestões de modelos via IA Local' },
  { version: '1.28.00', feature: 'Remoção da geração inline de embeddings' },
  { version: '1.27.00', feature: 'Busca Semântica na Jurisprudência' },
  { version: '1.26.00', feature: 'Busca Semântica na Legislação' },
  { version: '1.25.17', feature: 'Fuzzy Deduplication para nomes' },
  { version: '1.25.02', feature: 'IA Offline NER' },
  { version: '1.25.00', feature: 'Otimização de cache (economia ~40-50% tokens)' },
  { version: '1.24.00', feature: 'Sistema de Versionamento do campo fundamentação' },
  { version: '1.22.00', feature: 'Centralização prompts mini-relatórios' },
  { version: '1.21.21', feature: 'Botão "Revisar Sentença"' },
  { version: '1.21.20', feature: 'Filtro "Informativo" na jurisprudência' },
  { version: '1.21.00', feature: 'Anonimização completa provas' },
  { version: '1.20.00', feature: 'Fix duplicação tópicos + VirtualList' },
  { version: '1.19.00', feature: 'Chat interativo no assistente IA' },
  { version: '1.14.00', feature: 'Detecção TF-IDF de similaridade' },
];
