// Histórico de versões do SentencifyAI
// Extraído do App.jsx para melhor organização

export const CHANGELOG = [
  { version: '1.42.04', feature: 'feat(revisão): toggle "Excluir tópicos sem resultado" no modal de Revisar Sentença (default ON) — filtra tópicos com resultado SEM RESULTADO antes de enviar à IA, economizando tokens e focando a análise crítica nos pontos efetivamente decididos. Cache do IndexedDB usa chave composta (sufixo :noEmpty) para preservar resultados de ambos os modos em separado; caches antigos seguem válidos como flag desligada. Comparação case-insensitive para robustez. Toggle bloqueado durante geração; tema claro/escuro suportados.' },
  { version: '1.42.03', feature: 'UX(assistente): botão de web search reposicionado — agora aparece ao lado de "Toda a decisão" dentro do seletor de escopo (via novo prop extraSlot em ContextScopeSelector), em vez de acima do KnowledgePackageSelector. Layout mais coeso visualmente.' },
  { version: '1.42.02', feature: 'feat(assistente): toggle de busca na web no Assistente de Redação (Gemini). Opt-in por sessão, default OFF, bloqueado quando anonimização está ativa. Provider-agnostic via registry (src/utils/ai-tools/webSearch.ts) — expandir para Claude/OpenAI/Grok futuramente = adicionar adapter no registry, zero mudanças em call sites. Fontes consultadas aparecem abaixo da resposta em UI colapsável (ChatGroundingFooter) com links seguros via safeHref (rejeita javascript:/data:/etc). Acessibilidade: role=switch + aria-pressed + aria-expanded. 3 camadas de defesa contra ativação indevida (UI, hook, registry). +56 testes unitários.' },
  { version: '1.42.01', feature: 'UX(analisador): badge de "Ver Análises Salvas" agora mostra número correto em vez de travar em 99+. Círculo para 1-2 dígitos, pill com auto-width para 3+, abreviação com "k"/"M" a partir de 1000 (ex: 1,2k / 12k / 1,2M). Tooltip mostra número exato e total com plural correto.' },
  { version: '1.42.00', feature: 'feat(google-drive): sessão permanente via OAuth Authorization Code Flow com refresh token no backend — conecta uma vez, nunca mais relogar. Adicionada tabela google_drive_tokens (SQLite, refresh criptografado AES-256-GCM), serviço GoogleDriveAuthService + rotas /api/google-drive/{status,auth-url,callback,access-token,disconnect}. Frontend reescrito: connect() agora redireciona ao consentimento Google em vez de abrir popup; cada ação puxa access token do backend (que faz refresh server-to-server). Removida dependência @react-oauth/google. Logout do magic link agora revoga Google Drive também. REQUER configurar env vars no Render: GOOGLE_CLIENT_SECRET, GOOGLE_TOKEN_ENCRYPTION_KEY (gerar com node -e "console.log(require(\'crypto\').randomBytes(32).toString(\'hex\'))"), GOOGLE_DRIVE_REDIRECT_URI=https://sentencify.ia.br/api/google-drive/callback, e adicionar esse redirect URI no Google Cloud Console.' },
  { version: '1.41.24', feature: 'fix(google-drive): remover refresh proativo em background que introduzia log [GSI_LOGGER]: Failed to open popup — @react-oauth/google usa popup, não iframe, e o setTimeout do refresh proativo disparava fora da user activation do navegador, causando popup-blocker. Mantido apenas o silent refresh sob demanda (do clique em Carregar/Salvar), que funciona por estar dentro do gesto do usuário. Se a sessão Google também estiver expirada, o toast de reconectar orienta o usuário.' },
  { version: '1.41.23', feature: 'fix(editor): contraste do toolbar Quill no tema claro — botões ativos (negrito, itálico, etc.) herdavam fundo slate-600 do tema escuro, tornando ícones ilegíveis. Agora usa fundo azul-claro (#dbeafe) com ícones em azul-escuro (#1e3a8a), mantendo clara a indicação de formato ativo sem comprometer leitura.' },
  { version: '1.41.22', feature: 'fix(revisão): injetar data atual no system prompt de revisaoSentenca para evitar falsos positivos de "erro cronológico" — modelos como Gemini, sem âncora temporal, usavam a data de treino e flagavam datas de 2026 presentes na sentença como se fossem futuras. Agora o prompt informa a data de referência e instrui a IA a tratar apenas datas posteriores como futuras.' },
  { version: '1.41.21', feature: 'fix(google-drive): sessão expirada agora exibe aviso claro para reconectar — ao clicar Carregar/Salvar com token expirado e sessão Google também expirada, o silent refresh falha e o usuário recebe toast imediato orientando a clicar em "Projeto" no header (antes: travava 2 min porque o popup de fallback era bloqueado pelo navegador por ser disparado em contexto assíncrono fora de user gesture). Adicionado refresh proativo em background ~5 min antes da expiração — se a sessão Google estiver ativa, o token renova sozinho e o usuário nunca vê o toast. Removido o fluxo frágil de popup async (extendForPopup, TOKEN_POPUP_TIMEOUT_MS).' },
  { version: '1.41.20', feature: 'refactor(ai-config): eliminar duplicação de stores de IA entre apps — nova factory createAIStore em src/stores/shared/ + tipos consolidados em src/types/ai.ts; os 3 useAIStore.ts (analisador, noticias, prova-oral) caíram de ~210 linhas cada para ~30 linhas cada; os 3 ai.types.ts idênticos foram apagados; comportamento preservado (persist names, fallback chain de API keys, token metrics por app); +18 testes unitários para a factory.' },
  { version: '1.41.19', feature: 'fix(google-drive): corrigir race condition em handleLoginSuccess — resolve(token) agora é chamado antes do await fetch(userInfo), eliminando a janela onde o timer de 2min disparava enquanto o fetch de userInfo estava pendente; token também é persistido no localStorage mesmo quando o fetch de userInfo falha, evitando ciclos desnecessários de silent refresh.' },
  { version: '1.41.18', feature: 'fix(google-drive): corrigir timeout ao renovar sessão expirada via popup — timeout de 15s era mantido após silent refresh falhar e abrir popup, rejeitando a operação antes do usuário conseguir logar; agora extendForPopup() cancela o timer curto e inicia um de 2 min quando o fallback para popup é ativado.' },
  { version: '1.41.17', feature: 'UX(editor): largura do editor em tela cheia agora é ajustável pelo usuário — dropdown "Largura" na toolbar com 4 opções (Estreito 800px / Normal 1200px / Largo 1600px / Total 100%); visível apenas em tela cheia sem split view; preferência persiste no localStorage.' },
  { version: '1.41.16', feature: 'UX(editor): adicionar margens laterais confortáveis no modo tela cheia sem split view — editor agora usa max-width: 1200px centralizado; sem efeito no split view de modelos.' },
  { version: '1.41.15', feature: 'fix(custo): estimativa "Uso de Tokens" agora usa preço correto por modelo — Gemini 3.1 Pro usava preço do Flash ($0.50/$3.00 em vez de $2.00/$12.00); corrigido com getGeminiPrices() model-aware no byModel breakdown. Mesma correção já existia para Grok 4.20 vs 4.1.' },
  { version: '1.41.14', feature: 'fix(modelos): Grok 4.20-0309 não aparecia no main SentencifyAI — ConfigModal.tsx (select + type cast + nome), useAIStore.ts (setGrokModel type) e TopicCurationModal.tsx (pricing + nomes) não haviam sido atualizados na primeira rodada.' },
  { version: '1.41.13', feature: 'feat(modelos): adicionar Grok 4.20-0309 (reasoning e non-reasoning) como novas opções de modelo em todos os apps (SentencifyAI, Analisador, Prova Oral, Notícias) — mantém modelos Grok 4.1 existentes como padrão.' },
  { version: '1.41.12', feature: 'Fix(exportação): título "FUNDAMENTAÇÃO" agora exportado como <h2> — antes era <div> com estilo idêntico mas sem semântica de heading, fazendo Word e Google Docs tratar como texto comum; substituído por <h2 style=EXPORT_STYLES.h2> para consistência com RELATÓRIO e DISPOSITIVO. Remove chave obsoleta fundamentacaoHeader de export-styles.ts.' },
  { version: '1.41.11', feature: 'Estilo: adicionar regra 12 PRECISÃO REFERENCIAL E ELIMINAÇÃO DE AMBIGUIDADES SINTÁTICAS ao prompt estiloRedacao — combate apostos e particípios que, por proximidade sintática, podem referir-se a mais de um substantivo; aplica-se especialmente a datas, prazos e valores nos quais ambiguidade referencial gera consequências práticas na execução. Fix(testes): corrigir 18 falhas em chat-context-builder.test.ts — getLastTextItem retornava a instrução do usuário (último item separado) em vez do bloco principal; adicionado helper getAllText para checar conteúdo em qualquer item do array.' },
  { version: '1.41.10', feature: 'Fix(dispositivo): corrigir geração com nomes reais quando anonimização está desligada — buildPartesDoProcesso agora aceita flag anonymizationEnabled; quando OFF, injeta instrução explícita para usar nomes reais ao invés do mapeamento de placeholders [RECLAMANTE]/[RECLAMADA]; antes a IA criava placeholders mesmo sem anonimização ativa.' },
  { version: '1.41.09', feature: 'Fix(google-drive): auto-renovação de token OAuth — token expira após 1h; hook useGoogleDrive agora usa getValidToken() que verifica expiração antes de cada chamada à API Drive e, se necessário, executa silent refresh (prompt: none) sem interromper a operação; fallback para popup de login se silent falhar. Antes o usuário precisava deslogar e relogar manualmente.' },
  { version: '1.41.08', feature: 'fix(security): cap de 500 no parâmetro limit da paginação de despesas (financeiro-expenses.js) e validação de existência de usuários em recipientIds antes de inserir em prova_oral_access (prova-oral.js).' },
  { version: '1.41.07', feature: 'Fix(prompts): extrair bloco ANONIMIZAÇÃO DE DADOS de AI_INSTRUCTIONS_SAFETY para novo export condicional AI_INSTRUCTIONS_ANONYMIZATION — antes a instrução era sempre enviada no system prompt, fazendo a IA usar [VALOR]/[NOME] espontaneamente como placeholders mesmo sem anonimização ativa; agora o bloco só é injetado quando anonymization.enabled=true.' },
  { version: '1.41.06', feature: 'Fix(provas): autosave não disparava ao adicionar sub-anexos — computeProofsHash em useChangeDetectionHashes.ts agora inclui IDs dos attachments na assinatura do proofFilesSig; antes a hash era idêntica após add/remove de anexo, impedindo markSessionDirty de ser chamado.' },
  { version: '1.41.05', feature: 'UX(provas): seleção múltipla de PDFs no botão "+ PDF" da seção de Anexos — input agora tem atributo multiple e o handler itera sobre todos os arquivos selecionados, adicionando e salvando no IndexedDB em sequência.' },
  { version: '1.41.04', feature: 'Fix(provas): incluir anexos de provas no Export/Import de Projeto — exportProject serializa cada attachment com fileData (base64 do PDF) ou texto; importProjectFromJson restaura attachments criando File objects e salvando no IndexedDB via saveAttachmentToIndexedDB. Antes os sub-anexos eram perdidos ao exportar o projeto e reimportar.' },
  { version: '1.41.03', feature: 'Fix(provas): corrigir persistência de anexos após F5/reload — auto-save agora serializa metadados dos attachments no localStorage (id, name, type, extractedText, processingMode, text — sem file); restore reconstrói cada attachment restaurando o File do IndexedDB via getAttachmentFromIndexedDB. Antes do fix, todos os sub-anexos desapareciam ao recarregar a página.' },
  { version: '1.41.02', feature: 'Fix(provas): incluir anexos de provas no contexto do Assistente de Redação IA — prepareProofsContext e prepareOralProofsContext agora processam proof.attachments quando proofSendFullContent está ativo, respeitando o processingMode individual de cada anexo (pdf-puro envia binário; pdfjs/tesseract/claude-vision exige extractedText); anonimização bloqueia PDF binário com fallback para texto extraído.' },
  { version: '1.41.01', feature: 'Fix: bloquear radio buttons de Escopo do Contexto (Apenas este tópico / Tópicos selecionados / Toda a decisão) e dropdown de seleção de tópicos após a 1ª mensagem do chat — o contexto só é construído uma vez (1ª msg), então alterar o escopo depois não tinha efeito real. Visual igual aos checkboxes de documentos: opacity-60, cursor-not-allowed, aviso "Limpe o chat para alterar".' },
  { version: '1.41.00', feature: 'Pacotes de Conhecimento: novo recurso no Assistente de Redação IA (modo individual e global) — usuário cria pacotes com instruções personalizadas e arquivos de texto (acórdãos, trechos doutrinários etc.), seleciona antes da primeira mensagem, pacote é injetado no contexto inicial. Persistência no SQLite por usuário, cache offline no localStorage.' },
  { version: '1.40.33', feature: 'Refactor: migrar Auto Complete para useAIIntegration/callAI — elimina fetch direto duplicado, passa a contabilizar tokens no sistema centralizado de tracking (logMetrics: true), suporte automático a todos os providers configurados.' },
  { version: '1.40.32', feature: 'UX: campo de mensagem do Assistente de Redação IA agora cresce automaticamente conforme o texto digitado (auto-resize), com altura máxima de 200px e scroll interno. Volta ao tamanho inicial ao enviar.' },
  { version: '1.40.31', feature: 'Auto Complete com IA: sugestão de próxima frase em tempo real no editor de decisão (modo individual e global). Aparece em cinza claro/escuro após pausa configurável (1–10s, default 3s). Pressionar TAB aceita a sugestão; qualquer outra tecla descarta. Usa o provider e modelo de IA configurados. Ativável nas configurações de IA.' },
  { version: '1.40.30', feature: 'Estilo: adicionar regra SOBRIEDADE ASSERTIVA (evitar "voz de narrador") ao prompt de estilo — combate construções em que o texto anuncia o valor ou peso de algo antes de demonstrá-lo, padrão típico de LLM; regra 11 em estiloRedacao (ai-prompts.ts) e regra 6 em AI_INSTRUCTIONS_STYLE (system.ts)' },
  { version: '1.40.29', feature: 'Fix: corrigir itens de lista sumindo no tópico DISPOSITIVO — converter HTML padrão (<ul>/<li>) gerado pela IA para formato interno do Quill (<ol><li data-list="bullet">) antes de salvar editedContent; corrigir htmlToFormattedText para reconhecer <li> com atributos' },
  { version: '1.40.28', feature: 'Refactor: migrar análise de provas para streaming silencioso — remove StreamingModal (startStreaming/updateStreamingText/stopStreaming) dos handlers de análise; streaming acontece sem modal visível, exatamente como mini-reports. Remove workaround setShowStreamingModal(false) do useProofAnalysis.' },
  { version: '1.40.27', feature: 'Fix: fechar StreamingModal antes de abrir DoubleCheckReviewModal na análise de provas — evita sobreposição de modais quando double-check está ativo (setShowStreamingModal(false) antes de openDoubleCheckReview)' },
  { version: '1.40.26', feature: 'Streaming: ativar streaming na análise de provas (contextual e livre) via StreamingModal — elimina timeouts em análises longas, exibe texto em tempo real com título "Analisando Prova"' },
  { version: '1.40.25', feature: 'Fix: remover carregamento estático do Quill 1.3.6 via cdn.quilljs.com do index.html (causava erros de CORS); carregamento dinâmico do Quill 2.0.2 via jsdelivr pelo hook useQuillInitialization permanece como única fonte' },
  { version: '1.40.24', feature: 'Fix: corrigir nome de exibição "Gemini 3.0 Flash" → "Gemini 3 Flash" no seletor de provedor do app financeiro; atualizar comentário do proxy Gemini (server/routes/gemini.js) para refletir suporte a Gemini 3 / 3.1' },
  { version: '1.40.23', feature: 'Atualização: Gemini 3 Pro migrado para gemini-3.1-pro-preview em todos os apps (SentencifyAI, Notícias, Analisador, Prova Oral), substituindo modelo descontinuado em 9/mar/2026' },
  { version: '1.40.22', feature: 'Segurança: mover API key do Gemini da URL (?key=) para header (x-goog-api-key), evitando exposição em logs de proxy/CDN. Alinhado com padrão já usado por Claude/OpenAI/Grok' },
  { version: '1.40.21', feature: 'Exibir número do julgado ADI/ADC/ADPF na aba Jurisprudência: renderIdentificador() agora mostra "nº X" para precedentes com numeroProcesso, removida exibição redundante abaixo do título' },
  { version: '1.40.20', feature: 'Proteger QuickPrompts padrão de edição/exclusão: prompts default (qp-1 a qp-5) agora são readonly com indicador visual de cadeado, novos prompts personalizados continuam editáveis/excluíveis' },
  { version: '1.40.19', feature: 'Migrar extractedProofTexts para IndexedDB: textos de OCR de provas agora salvos no IndexedDB (evita estouro do localStorage). Migração automática de sessões antigas' },
  { version: '1.40.17', feature: 'Migrar textos de uploads para IndexedDB: pastedTexts, analyzedDocuments texts e extractedTexts agora salvos no IndexedDB (evita estouro do localStorage ~5-10MB). Migração automática de sessões antigas' },
  { version: '1.40.16', feature: 'Prova Oral: remover comentários do texto importado com marcações (importar apenas texto marcado, sem [💬 comentário])' },
  { version: '1.40.15', feature: 'Prova Oral: gerar sintesesCondensadas programaticamente (consistência garantida entre abas), atualizar prompts Fase 2 para classificar declarações por tema sem perder nenhuma, fix importação credibilidade exibindo dep-0X ao invés do nome (lookup em depoentes[])' },
  { version: '1.40.14', feature: 'Proteção contra truncamento de resposta da API: verificar stop_reason/finish_reason em todas as 8 funções de chamada (streaming e não-streaming) do useAIIntegration.ts - lançar erro informativo quando resposta exceder max_tokens' },
  { version: '1.40.13', feature: 'Fix bugs críticos: (1) Analisador tela branca quando tipoPedido inválido - adicionar guard em config[tipo] antes de desestruturar (PedidosSection.tsx, PedidoCard.tsx); (2) Prova-Oral "Processo não identificado" na importação - extrair número do nome do arquivo como fallback (server/routes/analyses.js)' },
  { version: '1.40.12', feature: 'Compartilhamento de análises de Prova Oral: seção nas configurações para selecionar usuários que podem ver suas análises, badge visual no histórico para análises compartilhadas, endpoints backend GET/PUT /api/prova-oral/sharing, migration 008 (prova_oral_access)' },
  { version: '1.40.11', feature: 'Edição inline de análises de prova: botão de editar aparece no hover, textarea editável com botões Cancelar/Salvar, persistência automática via Zustand store' },
  { version: '1.40.10', feature: 'Streaming para Confronto de Fatos: useFactsComparison agora usa callAIStream para evitar timeout de 30s no Render em operações longas' },
  { version: '1.40.09', feature: 'Fix estado compartilhado do modelo E5: migrar useSemanticSearchManagement de useState local para Zustand store (useSearchStore). Quando ConfigModal inicializa o modelo, TODOS os componentes (App.tsx, tabs) agora veem searchModelReady=true instantaneamente, sem precisar F5. Restaurar toast "Modelo de busca pronto!" que foi perdido na refatoração v1.40.06' },
  { version: '1.40.08', feature: 'Fix bug de auto-inicialização do modelo E5: restaurar useEffect removido acidentalmente na refatoração v1.40.06 (agora no hook useSemanticSearchManagement). Modelo E5 é auto-carregado após F5 quando toggle de Busca Semântica está habilitado' },
  { version: '1.40.07', feature: 'Limpeza pós-refatoração ConfigModal: remover variáveis e handlers não utilizados do App.tsx (~120 linhas removidas). TypeScript sem erros, 5904 testes passando' },
  { version: '1.40.06', feature: 'Refatoração ConfigModal: eliminar 52 props via import direto de hooks/stores (useAIStore, useUIStore, useModelsStore, useNERManagement, useSemanticSearchManagement, useEmbeddingsManagement, useLegislacao, useJurisprudencia, useDragDropTopics, useExportImport). Props reduzidas de 52 para 2 (96% redução)' },
  { version: '1.40.05', feature: 'Refatoração prop drilling: criar useEditorStore e useRegenerationStore (Zustand), expandir useModelsStore com preview contextual, reduzir props de DecisionEditorContainer de 54 para ~6 (89% redução)' },
  { version: '1.40.04', feature: 'Streaming silencioso para app Analisador: useAIIntegration e useAnalysis agora usam SSE para evitar timeout em análises longas de prepauta' },
  { version: '1.40.03', feature: 'Streaming silencioso para geração de relatório processual: generateRelatorioProcessual agora usa SSE para evitar timeout em operações longas' },
  { version: '1.40.02', feature: 'Streaming silencioso para Double Check e ordenação de tópicos: performDoubleCheck e reorderTopicsViaLLM agora usam SSE para evitar timeout em operações longas' },
  { version: '1.40.01', feature: 'Ativar streaming silencioso por padrão: mini-relatórios (useReportGeneration), análise de documentos (useDocumentAnalysis) e revisão de sentença (useReviewSentence) agora usam SSE para evitar timeout de 30s no Render sem mostrar texto parcial' },
  { version: '1.40.00', feature: 'Streaming para operações de IA: evita timeout do Render (30s) mostrando resposta em tempo real. Inclui StreamingModal compartilhado, funções callAIStream para todos os providers (Claude, Gemini, OpenAI, Grok), e integração opcional nos hooks useReportGeneration, useProofAnalysis e useDispositivoGeneration' },
  { version: '1.39.08', feature: 'Importar análise de Prova Oral na aba Provas: botão visível quando autenticado, modal de listagem com busca, seleção de seções (sínteses, contradições, confissões, credibilidade), transcrição vira ProofText + seções viram ProofAnalysisResult tipo importada' },
  { version: '1.39.07', feature: 'Fix toggle de tema no Analisador: adicionar darkMode class ao tailwind.config.js (antes: classes dark:* não tinham efeito)' },
  { version: '1.39.06', feature: 'Toggle para incluir/excluir documentos complementares no contexto do chat IA (desativado por padrão, persistido por tópico, sobrevive F5 e export/import)' },
  { version: '1.39.05', feature: 'Fix [object Object] na descricao de merge do Double Check: tratar correction.into como string ou objeto { title: string } (antes: IA retornava objeto e interpolacao mostrava [object Object])' },
  { version: '1.39.04', feature: 'Exibir data/hora audiencia no ResultsContainer (ao abrir analise do historico) + persistir estado expanded/collapsed dos grupos de pauta no HistoricoModal (localStorage)' },
  { version: '1.39.03', feature: 'Consolidar retry logic: centralizar 7 implementacoes duplicadas em src/utils/retry.ts (withRetry, withStorageRetry). Reducao de ~200 linhas de codigo duplicado' },
  { version: '1.39.02', feature: 'Fix wheel scroll durante drag no TopicCurationModal: redireciona wheel events para o scroll container (antes: wheel bloqueado porque target era o DragOverlay)' },
  { version: '1.39.01', feature: 'Fix scroll no TopicCurationModal: body scroll lock quando modal aberto, prevenção de scroll externo durante drag, handler para drag cancelado (ESC)' },
  { version: '1.39.00', feature: 'Eliminação total de any types: tipagem completa para APIs (Claude, OpenAI, Grok, Gemini), PDF.js e respostas de IA. 0 any types, 0 erros TypeScript, 88% cobertura, 5932 testes' },
  { version: '1.38.53', feature: 'Fix erros TypeScript em arquivos de teste: corrigir 10 erros de tipo (DOMPurify/Quill types, TopicCategory, PastedText[], imports não usados, variáveis não lidas). 0 erros TypeScript' },
  { version: '1.38.50', feature: 'Sprint 5 - Cobertura de testes de 60% para 86%: +2399 testes (5253 total), 133 arquivos de teste, 0 erros TypeScript. Cobertura: 86% linhas, 85% statements, 76% branches, 84% funções' },
  { version: '1.38.49', feature: 'Fix anonimização de VALOR ativa mesmo quando desligada: preservarAnonimizacao agora condicional a anonymization.enabled nos prompts de mini-relatório e relatório processual' },
  { version: '1.38.48', feature: 'Redução de dívida técnica: strip console em produção (esbuild.drop), corrigir catch blocks vazios, eliminar any types (schemas Zod tipados), habilitar noUnusedLocals/Parameters e remover ~559 imports mortos' },
  { version: '1.38.47', feature: 'Default "Incluir petições e contestações" desativado: toggle inicia desligado para economizar tokens (antes: ativado por padrão)' },
  { version: '1.38.46', feature: 'Fix ditado por voz ignora modelo selecionado: corrigir stale closure no useVoiceToText (onTranscript capturava modelo antigo em gravações subsequentes) usando ref pattern' },
  { version: '1.38.45', feature: 'Fix import de projeto sobrescreve API keys: ler keys decriptadas do Zustand store ao invés do localStorage (onde estão criptografadas), evitando double-encryption que inutilizava as chaves' },
  { version: '1.38.44', feature: 'Fix Gemini gasta todos os tokens em thinking: adicionar thinking_budget explícito no thinking_config (cap: 2000/4000/8000/16000 conforme nível) para garantir tokens restantes para resposta textual' },
  { version: '1.38.43', feature: 'Fix PDFs perdidos após import + F5: autoSave agora grava IDs dos arquivos restaurados no localStorage (antes gravava arrays vazios, deixando PDFs órfãos no IndexedDB)' },
  { version: '1.38.42', feature: 'Busca expandida no Google Drive: além da pasta Sentencify, busca arquivos sentencify-*.json em qualquer local do Drive + campo de busca por nome no modal de arquivos' },
  { version: '1.38.41', feature: 'Fix caches IndexedDB de projetos anteriores persistindo: importProject e clearProject agora limpam chat-history, facts-comparison, sentence-review e versions antes de carregar novo projeto' },
  { version: '1.38.40', feature: 'Fix batch analysis: stagger delay 1.5s entre requests concorrentes (evita respostas truncadas) + retry automático (max 2x) quando parsing da resposta IA falha' },
  { version: '1.38.39', feature: 'Fix API keys não persistindo em F5: setAiSettings agora detecta mudanças em apiKeys e persiste em sentencify-ai-settings (ConfigModal usava setAiSettings que bypassava a persistência)' },
  { version: '1.38.38', feature: 'Fix CSP para modelos HuggingFace (adiciona cas-bridge.xethub.hf.co) + Quick Prompts não carregando na primeira visita (fallback para defaults no onRehydrateStorage)' },
  { version: '1.38.37', feature: 'Fix confidence hardcoded: todas as 6 operações Double Check agora usam confidence retornado pela IA (antes: 5 de 6 usavam 85% fixo)' },
  { version: '1.38.36', feature: 'Double Check: aplicação parcial de correções (topicExtraction/factsComparison) + usar confidence retornado pela IA ao invés de 85% hardcoded' },
  { version: '1.38.35', feature: 'UX Double Check quickPrompt: mostrar "🔍 Verificando resposta..." no chat enquanto Double Check roda (usuário não vê resposta antes da verificação)' },
  { version: '1.38.34', feature: 'Fix Double Check quickPrompt: retornar response diretamente de send() para evitar race condition com lastResponse memoizado (antes: Double Check não rodava na primeira interação)' },
  { version: '1.38.33', feature: 'Fix análise de provas: proibir IA de "pescar" documentos mencionados no contexto - deve analisar APENAS o documento na tag <prova-principal>' },
  { version: '1.38.32', feature: 'Prompt profissional para análise de provas documentais: engenharia de prompt avançada (role/persona, chain of thought, few-shot examples, guardrails) + lógica exclusiva prova oral vs documental' },
  { version: '1.38.31', feature: 'Fix análise de prova: remover complementares do contexto (só petição+contestação) + tags XML para demarcação clara <PETICAO_INICIAL>, <CONTESTACAO>' },
  { version: '1.38.30', feature: 'Reforço prompt Double Check em TODOS os prompts de texto livre: dispositivo e sentenceReview também recebem instrução enfática (complemento v1.38.29)' },
  { version: '1.38.29', feature: 'Reforço prompt Double Check: instrução enfática para IA incorporar correções no verifiedResult (problema intermitente onde IA ignorava a instrução)' },
  { version: '1.38.28', feature: 'Fix "i is not iterable" na análise de provas: migração formato antigo→array no restore de sessão + optional chaining seguro' },
  { version: '1.38.27', feature: 'Múltiplas análises por prova (max 5): array de análises com UI de lista, botão excluir individual, FIFO automático (6ª análise remove a mais antiga), migração de dados antigos, todas enviadas ao assistente IA' },
  { version: '1.38.26', feature: 'UX provas: tooltips explicativos nos botões Analisar/Vincular quando desabilitados por anonimização + PDF puro' },
  { version: '1.38.25', feature: 'Fix contraste aviso CNJ no tema claro: text-amber-700/600 → text-amber-900/800 para melhor legibilidade' },
  { version: '1.38.24', feature: 'Remover aliases testStatus: ConfigModal agora usa useAIStore diretamente (8 aliases + 8 props removidos do App.tsx, ~30 linhas de boilerplate)' },
  { version: '1.38.23', feature: 'Migração Zustand completa: 4 hooks migrados para seletores diretos (useModalManager, useTopicManager, useProofManager, useModelLibrary) + remoção de 4 *Compat wrappers dos stores (~210 linhas de código morto)' },
  { version: '1.38.22', feature: 'Completar migração Zustand: remover useAISettingsCompat deprecated - useAIIntegration agora usa seletores diretos do store' },
  { version: '1.38.21', feature: 'Centralizar buildContextForChat: ~280 linhas duplicadas → função única em chat-context-builder.ts + remover ~170 linhas de código morto (generateGlobalAiText, insertGlobalAiText nunca chamados)' },
  { version: '1.38.20', feature: 'Estagiário Socrático: IA pergunta ratio decidendi antes de redigir comandos vagos no chat (ex: "Indefira as horas extras" → pergunta qual fundamento usar)' },
  { version: '1.38.19', feature: 'Contexto jurídico no prompt de melhoria de ditado: IA agora reconhece termos latinos, siglas (CLT, TST, OJ) e vocabulário técnico trabalhista' },
  { version: '1.38.18', feature: 'ChangelogModal com altura dinâmica por item: lista simples substitui VirtualList (textos não são mais cortados)' },
  { version: '1.38.17', feature: 'Fix scroll duplo no ChangelogModal: overflow-hidden no wrapper (só VirtualList rola)' },
  { version: '1.38.16', feature: 'Toggle "Incluir petições e contestações" persistido por tópico: bloqueado quando chat tem histórico (limpe para alterar), salvo em IndexedDB (sobrevive F5), incluído em export/import de projeto' },
  { version: '1.38.15', feature: 'Prompt especializado para análise de prova oral trabalhista: instruções de valoração correta de depoimentos pessoais (só confissão) vs testemunhais (prova a favor), síntese valorativa adaptada aos tópicos vinculados' },
  { version: '1.38.14', feature: 'Fix migração quickPrompts: sessões pré-v1.38.12 agora recebem proofFilter:oral via onRehydrateStorage (quick prompt Análise de Prova Oral funciona para usuários existentes)' },
  { version: '1.38.13', feature: 'VirtualList no ChangelogModal: renderiza só ~15-20 items visíveis (antes: 430+ DOM nodes) - performance' },
  { version: '1.38.12', feature: 'Controle granular de contexto no Assistente IA: escopo de tópicos (atual/selecionados/todos) + toggle petições/contestações + fix proofFilter oral no quick prompt' },
  { version: '1.38.11', feature: 'Fix crítico: chat do Assistente IA agora recebe petição inicial completa (antes: type mismatch peticao/peticoes causava petição ser ignorada)' },
  { version: '1.38.10', feature: 'Anexos de provas: dropdown de modo de extração (PDF.js, Tesseract, Claude Vision, PDF Binário) por anexo + clique em "Extraído: X caracteres" abre preview do texto' },
  { version: '1.38.9', feature: 'Expandir área útil: layout usa 95% da tela (antes: 1280px fixo), padding reduzido de 24px para 16px' },
  { version: '1.38.8', feature: 'Anexos em provas: permite adicionar documentos relacionados (impugnações, esclarecimentos) a uma prova principal, análise com delimitadores XML para IA distinguir prova principal de anexos' },
  { version: '1.38.7', feature: 'Reload automático no Assumir Controle: não precisa mais pressionar F5 (standalone não tem restrição do sandbox)' },
  { version: '1.38.6', feature: 'Fix race condition no tab lock: mover leitura de sessionStorage para useEffect (evita StrictMode limpar TAKEOVER_KEY antes do claim)' },
  { version: '1.38.5', feature: 'Fix melhoria com IA no ditado: adicionar improveWithAI em todos os VoiceButtons (QuillDecisionEditor, AIRegenerationSection, AIAssistantBaseLegacy, ChatInput, PreviewModals)' },
  { version: '1.38.3', feature: 'CSP (Content Security Policy) headers: proteção contra XSS com whitelist de CDNs (Quill, PDF.js, Tesseract), APIs IA, Google OAuth/Drive, HuggingFace, GitHub Releases e Sentry' },
  { version: '1.38.2', feature: 'Fix ícone Grok invisível no tema escuro: usar text-gray-400 (cor única para ambos os temas, igual aos outros ícones)' },
  { version: '1.38.1', feature: 'Fix bulk upload rate limiting: bulkStaggerDelay padrão alterado de 0ms para 500ms - espaça requisições dentro de cada batch para evitar erro 429' },
  { version: '1.38.0', feature: 'Limpeza de código órfão: remover 4 funções não utilizadas do App.tsx (applyFormat, applyModelFormat, executeDeleteModel, checkSavedSession) - ~40 linhas de código morto' },
  { version: '1.37.99', feature: 'Fix exclusão de tópicos não selecionados: useTopicModalHandlers.confirmDeleteTopic agora remove de extractedTopics, selectedTopics e topicsToMerge (antes: só removia de selectedTopics)' },
  { version: '1.37.98', feature: 'Fix erro 403 ao atualizar arquivo existente no Drive: remover campo parents do metadata no PATCH (Google API não permite)' },
  { version: '1.37.97', feature: 'Toast de feedback ao salvar projeto no Google Drive: usar showToast ao invés de setError (antes: mensagem não aparecia)' },
  { version: '1.37.96', feature: 'Modal de confirmação ao excluir do Google Drive: substituir window.confirm por BaseModal estilizado' },
  { version: '1.37.95', feature: 'Fix sincronização chat entre editores: isOpen força reload do cache ao abrir modal (antes: clear em um editor não refletia no outro)' },
  { version: '1.37.94', feature: 'Fix cache chat Editor Individual: App.tsx agora usa useChatHistoryCache (antes: só GlobalEditorModal tinha cache), remoção de logs debug' },
  { version: '1.37.93', feature: 'Fix persistência chat: salvar histórico do tópico anterior antes de limpar ao fechar modal (antes: topicTitle já era undefined quando tentava salvar)' },
  { version: '1.37.92', feature: 'Persistência do histórico de chat do Assistente IA por tópico: persiste em F5, incluído em export/import de projeto, botão Limpar Chat para apagar' },
  { version: '1.37.91', feature: 'Contagem de tokens por modelo: breakdown por modelo usado no painel Uso de Tokens, custo real calculado por provider, persistência em sessão/projeto' },
  { version: '1.37.90', feature: 'Refatorar melhoria de voz: reutilizar callAI do useAIIntegration com provider override - tracking automático de tokens, código duplicado removido (~90 linhas)' },
  { version: '1.37.89', feature: 'Fix endpoints API melhoria de voz: corrigir 404 (claude/messages, gemini/generate, openai/chat, grok/chat)' },
  { version: '1.37.88', feature: 'Melhoria automática de texto ditado por voz com IA: toggle em Config IA permite escolher modelo rápido (Haiku/Flash/GPT-4o Mini/Grok Instant) para corrigir e tornar fluido o texto ditado antes de inserir' },
  { version: '1.37.87', feature: 'Ditado por voz no campo "Minhas Conclusões" na aba Provas: VoiceButton integrado ao ProofCard para transcrição de voz' },
  { version: '1.37.86', feature: 'Fix Double Check: preservar campos item/suggestion da IA (antes: sobrescritos com "Correção 1/2/3") + UX binária para texto livre (sentenceReview/proofAnalysis/quickPrompt aceita tudo ou rejeita tudo)' },
  { version: '1.37.85', feature: 'Fix cores ícones provedores IA: Claude roxo→laranja (branding oficial), Grok visível em tema claro (dark:text-gray-300)' },
  { version: '1.37.84', feature: 'DriveFilesModal seguir padrão BaseModal: ESC handler hierárquico (sub-modais primeiro) + scroll lock' },
  { version: '1.37.83', feature: 'Fix ícone Claude incorreto: substituir SVG inventado pelo logo oficial starburst do Bootstrap Icons' },
  { version: '1.37.82', feature: 'Fix Quill tema claro: restaurar estilos .quill-light-theme deletados em v1.37.80 - editor agora muda corretamente entre temas' },
  { version: '1.37.81', feature: 'Sistema color-free completo: sanitização de cores inline em 10 pontos de entrada (paste, IA, import projeto/modelos), clipboard matcher remove color/background do Ctrl+V preservando bold/italic, CSS fallback com color:inherit !important' },
  { version: '1.37.80', feature: 'Fix tema claro/escuro: sistema color-free no Quill editor - textos herdam cor do tema (antes: cores hardcoded ignoravam troca de tema), injectQuillLightStyles() removida' },
  { version: '1.37.79', feature: 'Remover truncações de conteúdo: fundamentação completa no dispositivo (antes: 200 chars), análise de prova aumentada de 50k para 200k chars (~50 páginas)' },
  { version: '1.37.78', feature: 'Fix race condition sync inicial: modelsLoaded prop impede sync antes de IndexedDB carregar (antes: local=0 causava full sync em todo F5) + logs diagnóstico trackChange' },
  { version: '1.37.77', feature: 'Fix trackChange para deletes via modal: useModelModalHandlers agora chama trackChange antes de remover modelo, permitindo sync correto (antes: pendingDeletes=0 causava full sync e ressurreição de modelos deletados)' },
  { version: '1.37.76', feature: 'Fix completo sync modelos ressuscitando: pendingChangesRef evita stale closure, comparação considera pending deletes (455 >= 456-1), logs detalhados de push' },
  { version: '1.37.75', feature: 'Fix bug sync modelos ressuscitando: usar useModelsStore.getState() como fonte de verdade para contagem local (antes: localStorage desatualizado causava full sync desnecessário que baixava modelos deletados)' },
  { version: '1.37.74', feature: 'ModalRoot expandido: modais de tópicos (RenameTopicModal, MergeTopicsModal, SplitTopicModal, NewTopicModal) movidos do App.tsx para ModalRoot (~37 linhas removidas) - handlers passados como props para operações com AI regeneration' },
  { version: '1.37.73', feature: 'ModalRoot com Zustand: 7 modais extraídos do App.tsx para componente centralizado (DeleteTopic, DeleteModel, DeleteAllModels, Export, SimilarityWarning, ExtractedModelPreview, BulkDiscardConfirm) - hooks useTopicModalHandlers, useModelModalHandlers, useProofModalHandlers criados' },
  { version: '1.37.72', feature: 'Estender fix Double Check para dispositivo e sentenceReview: instrução explícita para incorporar correções no verifiedResult' },
  { version: '1.37.71', feature: 'Logos dos provedores de IA: ícones SVG oficiais (Claude, Gemini, OpenAI, Grok) substituem bolinhas coloridas no seletor de provedores' },
  { version: '1.37.70', feature: 'Fix Double Check correções não aplicadas ao texto final: instrução explícita para IA incorporar correções no verifiedResult (proofAnalysis e quickPrompt)' },
  { version: '1.37.69', feature: 'Fix Double Check respondendo em inglês: instrução explícita de idioma (português brasileiro) adicionada a todos os prompts' },
  { version: '1.37.68', feature: 'Double Check multimodal: suporte a PDF binário (Claude/Gemini/OpenAI), contexto completo sem truncação, fallback texto para Grok' },
  { version: '1.37.67', feature: 'Análise de provas: remover fundamentação já escrita (editedContent) do contexto - análise agora baseada apenas em documentos originais/mini-relatórios' },
  { version: '1.37.66', feature: 'Fix modal Double Check: descrições de correções agora mostram item/suggestion legíveis ao invés de apenas "improve"' },
  { version: '1.37.65', feature: 'Double Check para Análise de Provas e Quick Prompts: verificação secundária com modal de revisão de correções (completude, coerência, precisão jurídica)' },
  { version: '1.37.64', feature: 'Fix Double Check factsComparison: campo "observacoes" → "observacao" (singular) alinhado com tipo TypeScript - elimina correções falsas da IA' },
  { version: '1.37.63', feature: 'Estilo de redação: preferir "dispensa/dispensado" em vez de "demissão/demitido" (terminologia juridicamente correta)' },
  { version: '1.37.62', feature: 'Fix Double Check factsComparison: usar dados reais da IA nas correções (código estava sobrescrevendo tema/field/newValue com valores fixos)' },
  { version: '1.37.61', feature: 'Double Check factsComparison: regras fix_row movidas para início do prompt com exemplos ✅/❌ - IA agora gera tema real, field válido e newValue preenchido' },
  { version: '1.37.60', feature: 'Fix API keys perdidas ao recarregar página: setApiKey agora persiste em sentencify-ai-settings (antes só gravava em memória Zustand, usuários novos perdiam keys ao recarregar)' },
  { version: '1.37.59', feature: 'DoubleCheckReviewModal: Modal obrigatório para revisão de correções do Double Check - usuário aceita/rejeita correções individualmente antes de aplicá-las (topicExtraction, dispositivo, sentenceReview, factsComparison)' },
  { version: '1.37.57', feature: 'Fix bug "cannot add property embedding, object is not extensible" - gerar embeddings para modelos existentes falhava por mutação direta de objetos frozen do Zustand/Immer' },
  { version: '1.37.56', feature: 'FASE 4: Modal Registry Pattern em useUIStore - 46 flags booleanas substituídas por openModals: ModalKey[] array, código mais limpo e escalável, mantém compatibilidade backwards com objeto modals' },
  { version: '1.37.55', feature: 'FASE 3: TopicsTab extraído para src/components/tabs/TopicsTab.tsx (~252 linhas removidas) - aba Tópicos com DND, SortableTopicCard, botões ação (Unir/Novo/Editor Global/Revisar/Dispositivo/Exportar)' },
  { version: '1.37.54', feature: 'FASE 2: ProofsTab extraído para src/components/tabs/ProofsTab.tsx (~130 linhas removidas) - aba Provas com upload PDF/texto e ProofCard list' },
  { version: '1.37.53', feature: 'Limpeza App.tsx: removidos ~169 linhas de comentários obsoletos (extraído/movido) - imports reorganizados por categoria' },
  { version: '1.37.52', feature: 'Fix SentenceReviewModals: migrado para BaseModal com scroll lock e visual consistente (antes usava CSS.modalOverlay diretamente)' },
  { version: '1.37.51', feature: 'Extração de modais: Toast, AutoSaveIndicator, ChangelogModal, SentenceReviewModals, DownloadModals extraídos do App.tsx (~400 linhas removidas) - 7 novos componentes em src/components/' },
  { version: '1.37.50', feature: 'Fix bug categoria de tópicos: MERITO → MÉRITO (typo sem acento) em TopicCard.tsx e FullscreenModelPanel.tsx - tópicos agora preservam categoria correta após curadoria' },
  { version: '1.37.49', feature: 'Zustand Migration: 18 useState migrados para stores (useUIStore, useAIStore, useModelsStore) - driveFiles, modelGenerator, changelog, autoSaveDirty, error, copySuccess, anonymizationNamesText, partesProcesso, exportedText/Html, processoNumero, apiTestStatuses, useSemanticManualSearch, receivedModels, activeSharedLibraries' },
  { version: '1.37.48', feature: 'Fix encoding UTF-8: "Minhas Conclusões" na aba Provas (ProofCard.tsx)' },
  { version: '1.37.47', feature: 'Fix Vite warning: imports dinâmicos removidos em QuillEditors.tsx (FullscreenModelPanel, VersionSelect) - já estavam no bundle via barrel export' },
  { version: '1.37.46', feature: 'FASE 51: useMultiTabSync extraído para src/hooks/ (~52 linhas removidas) - sincronização multi-tab simplificada com Zustand getState() eliminando refs' },
  { version: '1.37.45', feature: 'FASE 47: useModelSuggestions extraído para src/hooks/ (~216 linhas removidas) - findSuggestions, refineWithAI, scoreModel com estratégia Zustand (useModelsStore.getState())' },
  { version: '1.37.44', feature: 'FASE 52: useSemanticSearchHandlers extraído para src/hooks/ (~35 linhas removidas) - busca semântica de modelos usando Zustand getState() para acesso direto ao store' },
  { version: '1.37.43', feature: 'FASE 44: useReviewSentence extraído para src/hooks/ (~82 linhas removidas) - estados e função de revisão crítica de sentença com cache e double check' },
  { version: '1.37.42', feature: 'FASE 43+48-50: useQuillInitialization, useTopicValidation, useKeyboardShortcuts, useEditorHandlers extraídos para src/hooks/ (~380 linhas removidas) - App.tsx 6400→6020 linhas' },
  { version: '1.37.41', feature: 'FASE 40-42: useNERManagement, useChangeDetectionHashes, useSemanticSearchManagement extraídos para src/hooks/ (~160 linhas removidas do App.tsx) - estados NER, hashes de detecção de mudanças, busca semântica E5' },
  { version: '1.37.40', feature: 'Fix encoding UTF-8 em GlobalEditorModal, useDocumentAnalysis, ModelsTab, FullscreenModelPanel - ~40 strings/comentários com acentos perdidos (Sugestões, Tópicos, Decisão, Visualização, etc.)' },
  { version: '1.37.39', feature: 'Fix encoding UTF-8 em ProofCard.tsx - ~25 strings com acentos perdidos (Tópicos, Análise, extração, binário, anonimização, etc.)' },
  { version: '1.37.38', feature: 'FASE 29: Toast system migrado para useUIStore - toast, showToast, clearToast centralizados no Zustand (~12 linhas removidas do App.tsx)' },
  { version: '1.37.37', feature: 'FASE 35+32: useThemeManagement e useTabbedInterface extraídos para src/hooks/ (~40 linhas removidas do App.tsx)' },
  { version: '1.37.36', feature: 'Fix RELATÓRIO duplicado: buildAnalysisPrompt extraído para src/prompts/ com acentos corretos (~95 linhas removidas de useDocumentAnalysis)' },
  { version: '1.37.35', feature: 'Fix RELATÓRIO não reconhecido como tópico especial: título/categoria criados sem acento não batiam com SPECIAL_TOPICS (corrigido em 3 arquivos)' },
  { version: '1.37.34', feature: 'Fix bug RELATÓRIO duplicado: acento perdido no filtro (linha 885 useDocumentAnalysis) causava comparação "RELATÓRIO" !== "RELATORIO" sempre true' },
  { version: '1.37.33', feature: 'HOTFIX: Corrigir encoding UTF-8 em ~30 arquivos - acentos perdidos em strings de usuário (Posição Fixa, Gerando relatório, etc.) + sinônimos jurídicos + mensagens de progresso' },
  { version: '1.37.32', feature: 'FASE 28: UploadTab extraído para src/components/tabs/UploadTab.tsx (~630 linhas) - aba de Upload com 3 seções (Petição, Contestação, Complementares) + paste text + ProcessingModeSelector' },
  { version: '1.37.31', feature: 'FASE 27: ModelsTab extraído para src/components/tabs/ModelsTab.tsx (~512 linhas) - aba Banco de Modelos com 8 seções (banner, header, ModelFormModal, filtros, semântica, grid/lista, paginação, empty states)' },
  { version: '1.37.30', feature: 'FASE 26: ConfigModal extraído para src/components/modals/ConfigModal.tsx (~2.154 linhas removidas) - modal de configurações com 18 seções (providers, API keys, thinking, double check, PDF, NER, embeddings, etc.)' },
  { version: '1.37.29', feature: 'Fix z-index SimilarityWarningModal (60→100) - modal agora aparece na frente do BulkReviewModal + mover bulk-prompts.ts para src/prompts/' },
  { version: '1.37.28', feature: 'FASE 20: useFileHandling extraído para src/hooks/ (~594 linhas removidas) - getBulkPendingFilesCount, handleConfirmBulkCancel, generateModelsFromFileContent, processBulkFiles, handleBulkFileUpload, saveBulkModels, removeBulkReviewModel, toggleFavorite + bulk-prompts.ts' },
  { version: '1.37.27', feature: 'FASE 25: useSlashMenu extraído para src/hooks/ (~99 linhas removidas) - openSlashMenu, closeSlashMenu, navigateSlashMenu, selectModelFromSlash, updateSlashSearchTerm + useEffects' },
  { version: '1.37.26', feature: 'FASE 21: useDecisionExport extraído para src/hooks/ (~152 linhas removidas) - exportDecision para exportação da sentença com clipboard e HTML' },
  { version: '1.37.25', feature: 'FASE 18: useExportImport extraído para src/hooks/ (~204 linhas removidas) - exportAiSettings, importAiSettings, exportModels, importModels, checkDuplicate' },
  { version: '1.37.24', feature: 'FASE 17: useDetectEntities extraído para src/hooks/ (~243 linhas removidas) - detectarNomesAutomaticamente, constantes NER (STOP_WORDS_*, GENTILIC_WORDS, ORG_STOP_WORDS)' },
  { version: '1.37.23', feature: 'FASE 19: html-conversion.ts extraído para src/utils/ (~228 linhas removidas) - htmlToPlainText, htmlToFormattedText, plainTextToHtml, cleanHtmlForExport' },
  { version: '1.37.22', feature: 'FASE 16: useModelExtraction extraído para src/hooks/useModelExtraction.ts (~340 linhas removidas) - extractModelFromDecisionText, saveExtractedModel, cancelExtractedModel' },
  { version: '1.37.21', feature: 'FASE 15: useFactsComparison extraído para src/hooks/useFactsComparison.ts (~210 linhas removidas) - handleOpenFactsComparisonIndividual, handleGenerateFactsComparisonIndividual, estados e cache' },
  { version: '1.37.20', feature: 'FASE 14: injectQuillStyles + injectQuillLightStyles extraídos para src/utils/quill-styles-injector.ts (~390 linhas removidas)' },
  { version: '1.37.19', feature: 'Índice desatualizado removido do App.tsx (~95 linhas) - header simplificado aponta para estrutura modular (src/hooks, src/stores, src/components, etc.)' },
  { version: '1.37.18', feature: 'FASE 12-13: useDecisionTextGeneration + promptBuilders extraídos (~680 linhas removidas) - generateAiText, insertAiText, buildContextForChat, handleSendChatMessage, generateAiTextForModel + buildDocumentContentArray, buildMiniReportPrompt' },
  { version: '1.37.16', feature: 'FASE 11: useDispositivoGeneration extraído (~425 linhas removidas) - generateDispositivo, regenerateDispositivoWithInstruction movidos para src/hooks/useDispositivoGeneration.ts' },
  { version: '1.37.15', feature: 'Fix "Gerar com IA" (título/keywords): useModelGeneration agora lê conteúdo diretamente do Quill editor via modelEditorRef (antes usava modelLibrary.newModel.content que não sincroniza em tempo real)' },
  { version: '1.37.14', feature: 'FASE 10: useModelSave extraído (~380 linhas removidas) - saveModel, saveModelWithoutClosing, executeSaveModel, executeSaveAsNew, executeExtractedModelSave, processBulkSaveNext, handlers de similaridade movidos para src/hooks/useModelSave.ts' },
  { version: '1.37.13', feature: 'Remove cache de "Gerar com IA" (título/keywords) - cada clique gera nova resposta da IA (se o usuário clica de novo, é porque quer resposta diferente)' },
  { version: '1.37.12', feature: '(revertido em v1.37.13) Fix cache hit com clear→setTimeout→set' },
  { version: '1.37.11', feature: 'Fix "Gerar com IA" sync: ModelFormModal agora sincroniza localModel quando Zustand newModel.title/keywords mudam' },
  { version: '1.37.10', feature: 'Fix parcial useModelGeneration: stale closure em setNewModel corrigida com functional updater (prev => ...)' },
  { version: '1.37.9', feature: 'FASE 8 LegalDecisionEditor: useEmbeddingsManagement extraído (~400 linhas removidas) - importação, download CDN, limpeza e geração de embeddings (legislação, jurisprudência, modelos)' },
  { version: '1.37.8', feature: 'FASE 7 LegalDecisionEditor: useModelGeneration extraído (~155 linhas removidas) - generateKeywordsWithAI, generateTitleWithAI para geração de keywords/título via IA' },
  { version: '1.37.7', feature: 'FASE 6 LegalDecisionEditor: useTopicOperations extraído (~165 linhas removidas) - handleRenameTopic, handleMergeTopics, handleSplitTopic, handleCreateNewTopic + plainTextToHtml para utils/text.ts' },
  { version: '1.37.6', feature: 'FASE 5 LegalDecisionEditor: useDragDropTopics extraído (~183 linhas removidas) - handlers de drag & drop para tópicos principais e complementares' },
  { version: '1.37.5', feature: 'FASE 4 LegalDecisionEditor: useTopicOrdering extraído (~107 linhas removidas) - reorderTopicsViaLLM (Art. 337 CPC)' },
  { version: '1.37.4', feature: 'FASE 3 LegalDecisionEditor: useProofAnalysis extraído (~222 linhas removidas)' },
  { version: '1.37.3', feature: 'FASE 2 LegalDecisionEditor: useReportGeneration extraído (~314 linhas removidas)' },
  { version: '1.37.2', feature: 'FASE 1 LegalDecisionEditor: useDocumentAnalysis extraído (~1036 linhas removidas) - analyzeDocuments, handleCurationConfirm, etc.' },
  { version: '1.37.1', feature: 'FASE 7 refatoração final: ErrorBoundary extraído para src/components/ErrorBoundary.tsx (~152 linhas removidas)' },
  { version: '1.37.0', feature: 'FASE 6 refatoração final: src/styles/ criado com GlobalHoverStyles e ThemeStyles (~1316 linhas removidas)' },
  { version: '1.36.99', feature: 'FASE 5 refatoração final: GlobalEditorModal extraído para src/components/modals/ (~1572 linhas removidas)' },
  { version: '1.36.98', feature: 'FASE 4 refatoração final: LockedTabOverlay extraído para src/components/ui/ (~261 linhas removidas)' },
  { version: '1.36.97', feature: 'FASE 3 refatoração final: GlobalEditorSection e DecisionEditorContainer extraídos para src/components/editors/ (~370 linhas removidas)' },
  { version: '1.36.96', feature: 'FASE 2 refatoração final: prepareDocumentsContext, prepareProofsContext, prepareOralProofsContext, fastHashUtil extraídos para src/utils/context-helpers.ts (~260 linhas removidas)' },
  { version: '1.36.95', feature: 'FASE 1 refatoração final: CSS, RESULTADO_STYLES extraídos para src/constants/styles.ts + INSTRUCAO_NAO_PRESUMIR extraído para src/prompts/instrucoes.ts (~90 linhas removidas)' },
  { version: '1.36.94', feature: 'Quill Editors + TIER 3 pendências extraídos: QuillEditorBase, QuillModelEditor, QuillDecisionEditor, QuillMiniRelatorioEditor, AIRegenerationSection, FieldEditor, InlineFormattingToolbar, ModelFormModal, ModelPreviewModal (~1787 linhas removidas)' },
  { version: '1.36.93', feature: 'TIER 3 componentes extraídos: ModelFormFields (forms/), SlashCommandMenu (ui/), JurisprudenciaModal (modals/) (~616 linhas removidas)' },
  { version: '1.36.92', feature: 'TIER 2 modais extraídos para AdvancedModals.tsx: ShareLibraryModal, AcceptSharePage, DispositivoModal, BulkReviewModal, BulkUploadModal (~1215 linhas removidas)' },
  { version: '1.36.91', feature: 'TIER 1 modais extraídos para MiscModals.tsx: AnalysisModal, ExportModal, AnonymizationNamesModal, LinkedProofsModal (~288 linhas removidas)' },
  { version: '1.36.90', feature: 'AI Assistant components extraídos para src/components/ai/: AIAssistantBaseLegacy, AIAssistantBase, AIAssistantModal, AIAssistantGlobalModal, AIAssistantModelModal + helpers (extractPlainText, isOralProof, hasOralProofsForTopic) (~685 linhas removidas)' },
  { version: '1.36.89', feature: 'Proof modals extraídos: ProofAnalysisModal, LinkProofModal adicionados a ProofModals.tsx (~230 linhas removidas)' },
  { version: '1.36.88', feature: 'Model extraction modals extraídos: ExtractModelConfirmModal, ExtractedModelPreviewModal, SimilarityWarningModal (~290 linhas removidas)' },
  { version: '1.36.87', feature: 'Panel components extraídos para src/components/panels/: FullscreenModelPanel, ModelSearchPanel, JurisprudenciaTab, LegislacaoTab (~1160 linhas removidas)' },
  { version: '1.36.86', feature: 'Card components extraidos para src/components/cards/: TopicCard, SortableTopicCard, ModelCard, ProofCard, VirtualList (~1140 linhas removidas)' },
  { version: '1.36.85', feature: 'Modais simples extraídos para src/components/modals/: BaseModal, ModalFooter, ModalWarningBox, ModalInfoBox, ModalAmberBox, ModalContentPreview + TopicModals, ModelModals, ProofModals, SessionModals, BulkModals, TextPreviewModal (~580 linhas removidas)' },
  { version: '1.36.84', feature: 'Chat components extraídos: ChatBubble, ChatHistoryArea, ChatInput, InsertDropdown para src/components/chat/ (~185 linhas removidas)' },
  { version: '1.36.83', feature: 'Mais UI components extraídos: VersionCompareModal, VersionSelect para src/components/version/ + JurisprudenciaCard, ArtigoCard para src/components/cards/ (~460 linhas removidas)' },
  { version: '1.36.82', feature: 'UI components extraídos: SuggestionCard, SplitDivider para src/components/cards/ + SpacingDropdown, FontSizeDropdown, ProcessingModeSelector para src/components/ui/ (~147 linhas removidas)' },
  { version: '1.36.81', feature: 'Serviços e utilitários extraídos: EmbeddingsServices.ts (~540 linhas), jurisprudencia.ts (~420 linhas), text.ts (~200 linhas), models.ts (~30 linhas) - App.tsx reduzido para ~28,900 linhas' },
  { version: '1.36.80', feature: 'useAIIntegration extraído para src/hooks/ (~1310 linhas removidas) + API_BASE extraído para src/constants/api.ts' },
  { version: '1.36.79', feature: 'useQuillEditor e useDocumentServices extraídos para src/hooks/ (~30KB removidos) + sanitizeQuillHTML' },
  { version: '1.36.78', feature: 'useModalManager e useModelLibrary extraídos para src/hooks/ (~14KB removidos) + searchModelsInLibrary, removeAccents, SEARCH_STOPWORDS, SINONIMOS_JURIDICOS' },
  { version: '1.36.77', feature: 'useTopicManager extraído para src/hooks/ (wrapper sobre Zustand store)' },
  { version: '1.36.76', feature: 'useProofManager e useDocumentManager extraídos para src/hooks/ (~486 linhas removidas)' },
  { version: '1.36.75', feature: 'useLocalStorage extraído para src/hooks/ (~1070 linhas removidas) + PDF IndexedDB helpers + APP_VERSION centralizado' },
  { version: '1.36.74', feature: 'useModelPreview extraído para src/hooks/ (~107 linhas removidas)' },
  { version: '1.36.73', feature: 'useChatAssistant extraído para src/hooks/ (~115 linhas removidas) + MAX_CHAT_HISTORY_MESSAGES' },
  { version: '1.36.72', feature: 'useJurisprudencia extraído para src/hooks/ (~210 linhas removidas) + helpers (IRR_TYPES, isIRRType, JURIS_TIPOS_DISPONIVEIS, JURIS_TRIBUNAIS_DISPONIVEIS, IndexedDB helpers)' },
  { version: '1.36.71', feature: 'useLegislacao extraído para src/hooks/ (~180 linhas removidas) + helpers (LEIS_METADATA, getLeiFromId, sortArtigosNatural, IndexedDB helpers)' },
  { version: '1.36.70', feature: 'Testes REAIS para 9 hooks extraídos (411 testes passando), regra #10 CLAUDE.md (testes devem importar código de produção), deletados 6 testes inefetivos' },
  { version: '1.36.69', feature: 'FASE 3 TIER 1: useIndexedDB extraído para src/hooks/ + validateModel, sanitizeModel (~527 linhas removidas)' },
  { version: '1.36.68', feature: 'FASE 3 TIER 0 completo: useAPICache, usePrimaryTabLock, useFieldVersioning extraídos (~340 linhas removidas)' },
  { version: '1.36.67', feature: 'FASE 3: useThrottledBroadcast extraído para src/hooks/ (~50 linhas removidas)' },
  { version: '1.36.66', feature: 'FASE 3 Hooks TIER 0: useFullscreen, useSpacingControl, useFontSizeControl, useFeatureFlags extraídos para src/hooks/ (~245 linhas removidas)' },
  { version: '1.36.65', feature: 'Zustand Migration Wave 3: useProofManager migrado para useProofsStore.ts (~290 linhas removidas do App.tsx)' },
  { version: '1.36.64', feature: 'Zustand Migration Wave 3: useTopicManager migrado para useTopicsStore.ts (~180 linhas removidas do App.tsx)' },
  { version: '1.36.63', feature: 'Zustand Migration Wave 3: useModelLibrary migrado para useModelsStore.ts (core data, busca, filtros, formulário)' },
  { version: '1.36.62', feature: 'Zustand Migration Wave 2: useAIIntegration config/tokenMetrics migrado para useAIStore.ts (~80 linhas removidas)' },
  { version: '1.36.61', feature: 'Zustand Migration: useModalManager migrado para store global (src/stores/useUIStore.ts), devtools habilitado para debug' },
  { version: '1.36.60', feature: 'Fix Double Check factsComparison: correções agora são aplicadas na tabela (faltava caso para verifiedResult no performDoubleCheck)' },
  { version: '1.36.59', feature: 'Fix indicação "Modelo atual" na Config IA: agora exibe corretamente GPT-5.2/Grok 4.1 quando OpenAI ou Grok selecionado' },
  { version: '1.36.58', feature: 'Double Check para Confronto de Fatos: verifica completude, classificação e correção das alegações na tabela comparativa' },
  { version: '1.36.57', feature: 'Cache infinito para Revisar Sentença: persiste entre sessões (IndexedDB) e em export/import de projeto, badge de cache, botão regenerar' },
  { version: '1.36.56', feature: 'Double Check: novas operações Dispositivo e Revisar Sentença, dropdown de Thinking Level por provider/modelo (Claude/Gemini/OpenAI/Grok)' },
  { version: '1.36.55', feature: 'Fix feedback visual copiar em busca semântica: Jurisprudência e Legislação agora mostram Check verde' },
  { version: '1.36.54', feature: 'Feedback visual ao copiar tese na aba Jurisprudência: ícone Check verde por 2 segundos' },
  { version: '1.36.53', feature: 'Fix busca semântica jurisprudência: campo "text" vs "texto" - TypeScript usava nome português mas JSON usa inglês' },
  { version: '1.36.52', feature: 'Fix texto IRR vazio em busca semântica: fallback para fullText/texto quando tese/enunciado não disponível (embeddings)' },
  { version: '1.36.51', feature: 'Fix contraste Double Check no tema claro: badges "(em breve)" e aviso de custo legíveis em ambos os temas' },
  { version: '1.36.50', feature: 'Double Check de respostas da IA: verificação secundária para extração de tópicos (falsos positivos, omissões, categorização), provider/modelo configurável' },
  { version: '1.36.49', feature: 'Toggle "Log thinking" desabilitado para modelos sem reasoning (Grok e GPT-5.2 Instant)' },
  { version: '1.36.48', feature: 'Fix layout AIAssistantBase: aviso CNJ e seletor de escopo agora dentro da área de scroll' },
  { version: '1.36.47', feature: 'Fix "Invalid Date" no modal compartilhar biblioteca: API retornava created_at (snake_case), frontend esperava createdAt' },
  { version: '1.36.46', feature: 'Fix ESC no ConfigModal: não fecha se ModelGeneratorModal (Gerar a partir de exemplos) aberto, evita perda de scroll' },
  { version: '1.36.45', feature: 'Fix ESC no GlobalEditorModal: fecha sub-modais (Jurisprudência/Assistente IA/Confronto) primeiro, reseta estados ao abrir' },
  { version: '1.36.44', feature: 'Deletar 16 arquivos de testes/hooks duplicados: 222 testes inúteis removidos (testavam código que não roda em produção)' },
  { version: '1.36.43', feature: 'Fix test failure: guard scrollIntoView em TopicCurationModal (JSDOM não implementa)' },
  { version: '1.36.42', feature: 'Build inclui tsc --noEmit: verificação de tipos antes do deploy (previne erros como ReferenceError)' },
  { version: '1.36.41', feature: 'Fix ReferenceError: usar documentServices.extractTextFromPDFWithMode (prefixo faltando)' },
  { version: '1.36.40', feature: 'Fix NER provas: usar extractTextFromPDFWithMode com modo selecionado (PDF.js ou Tesseract) ao invés de extractTextFromPDFPure' },
  { version: '1.36.39', feature: 'Fix NER em provas: "Detectar Nomes" agora extrai texto da PROVA (não da petição) - removido fallback incorreto' },
  { version: '1.36.38', feature: 'Aviso visual Grok na aba Provas: alerta laranja "Grok não suporta PDF binário" quando PDF sem texto extraído (similar ao aviso roxo de anonimização)' },
  { version: '1.36.37', feature: 'Fix bloqueio PDF com Grok: botão "Usar PDF" desabilitado no ProofCard, fallback para PDF completo bloqueado quando extração falha (anonimização/Grok), mensagem "extração obrigatória" em vermelho' },
  { version: '1.36.36', feature: 'Bloquear PDF Puro quando Grok selecionado: opção desabilitada nos seletores (Uploads e Provas), Claude Vision liberado' },
  { version: '1.36.35', feature: 'Fix estimativa de custo: mostrar modelo correto para OpenAI/Grok no TopicCurationModal (antes mostrava Claude)' },
  { version: '1.36.34', feature: 'Tesseract OCR: mais logs de diagnóstico (canvas render, OCR batch, cada página) para identificar gargalo' },
  { version: '1.36.33', feature: 'Tesseract OCR fix: primeiro worker baixa modelo sozinho (cacheia), depois cria demais em paralelo + logs de diagnóstico' },
  { version: '1.36.32', feature: 'Fix exclusão de prova: usar handleDeleteProof do hook (tipagem correta)' },
  { version: '1.36.31', feature: 'Fix exclusão de prova: String() na comparação de IDs (type mismatch number/string)' },
  { version: '1.36.30', feature: 'Fix botão excluir prova: race condition isOpen && proofToDelete no DeleteProofModal' },
  { version: '1.36.29', feature: 'Suporte PDF para OpenAI (type: file) + aviso Grok não suporta PDF binário nas abas Upload e Provas' },
  { version: '1.36.28', feature: 'Fix análise de provas: isPdf não setado na criação + verificação robusta com type === pdf' },
  { version: '1.36.27', feature: 'Fix background transparente no AIAssistantBase: adicionado overflow-y-auto flex-1 min-h-0 ao content' },
  { version: '1.36.26', feature: 'Fix stale cache Confronto ao trocar tópico: useEffect limpa resultado quando editingTopic muda' },
  { version: '1.36.25', feature: 'Fix contraste badges Confronto de Fatos no tema claro: cores -600 para tema claro, -400 para tema escuro' },
  { version: '1.36.24', feature: 'Fix cache Confronto de Fatos no editor individual: handleOpenFactsComparisonIndividual recupera cache do IndexedDB antes de abrir modal' },
  { version: '1.36.23', feature: 'Fix scroll BaseModal: min-h-0 no content div permite flexbox shrink e scroll interno funcionar corretamente' },
  { version: '1.36.22', feature: 'Fix Confronto de Fatos: fallback para PDF binário quando texto não extraído + scroll no BaseModal (max-h-[90vh] flex flex-col)' },
  { version: '1.36.21', feature: 'Refatorar FactsComparisonModal para usar BaseModal (padrão do app) + Botão Confronto no editor individual de tópicos + diretriz #6 no CLAUDE.md sobre uso obrigatório de BaseModal' },
  { version: '1.36.20', feature: 'Confronto de Fatos: botão na toolbar do editor abre modal para comparar alegações Petição vs Contestação vs Impugnação por tópico, tabela com fatos controversos/incontroversos, cache IndexedDB com TTL infinito, export/import no projeto' },
  { version: '1.36.19', feature: 'Fix UI edição prompts rápidos: campo de texto e onChange usavam name em vez de label (bug da migração TS)' },
  { version: '1.36.18', feature: 'Fix botões prompt rápido vazios (qp.name→qp.label) + nota sobre limitação Grok 4.x reasoning na API' },
  { version: '1.36.17', feature: 'Log thinking no console para Grok: toggle "Log thinking" agora funciona com Grok 4.1 Fast Thinking' },
  { version: '1.36.16', feature: 'Fix erro 502 Grok: formatar x-grok-conv-id como UUID4 válido (com hífens)' },
  { version: '1.36.15', feature: 'Fix espaçamento do checkbox "Log thinking no console" no Config IA Modal (mt-4)' },
  { version: '1.36.14', feature: 'Grok cache hit rate: header x-grok-conv-id baseado na API key para manter sessão de cache, log de cached tokens no servidor' },
  { version: '1.36.13', feature: 'UX: Auto-scroll e focus no MergeConfirm do TopicCurationModal - ao clicar "Mesclar", scroll suave para o formulário + cursor no campo de título' },
  { version: '1.36.12', feature: 'OpenAI/Grok na estimativa de custo: seção "Uso de Tokens" mostra 6 modelos (Claude Sonnet/Opus, Gemini Pro/Flash, OpenAI GPT-5.2, Grok 4.1) + "Limites por API" com 4 providers (grid responsivo)' },
  { version: '1.36.11', feature: 'UX: Indicador visual claro de thinking no Grok - badges "Thinking Embutido" (roxo) e "Sem Thinking" (âmbar) na seção Pensamento Prolongado' },
  { version: '1.36.10', feature: 'feat(multi-provider): Integração OpenAI GPT-5.2 + xAI Grok 4.1 - 4 providers (Claude, Gemini, OpenAI, Grok), reasoning configurável, Grok 96% mais barato que Claude' },
  { version: '1.36.9', feature: 'Fix bullet list no Quill: override ::before para data-list="bullet" (CSS do CDN não tem regra para bullets em <ol>)' },
  { version: '1.36.8', feature: 'Fix listas no Quill: list-style-type: none para evitar duplicação (Quill usa ::before para marcadores)' },
  { version: '1.36.7', feature: 'Fix lista bolinha: CSS respeita data-list, export converte <ol> bullet para <ul>, blockquote sem border-left' },
  { version: '1.36.6', feature: 'Fix exportação: listas bullet (data-list), indent (ql-indent-*), blockquote - DOMPurify agora permite atributos necessários' },
  { version: '1.36.5', feature: 'Fix exportação minuta: converter classes ql-align-* do Quill para inline styles (Google Docs ignora classes CSS)' },
  { version: '1.36.4', feature: 'Fix exportação minuta: preserva alinhamento do usuário (center, right) - remove align deprecated, corrige bug que sobrescrevia text-align' },
  { version: '1.36.3', feature: 'Fix exportação minuta: atributo align="center/justify" para Google Docs (style inline não era suficiente)' },
  { version: '1.36.2', feature: 'Fix exportação minuta: estilos inline para Google Docs (alinhamento centralizado/justificado preservado) - EXPORT_STYLES em src/constants/export-styles.ts' },
  { version: '1.36.1', feature: 'Fix race condition ao salvar modelo: dados passados diretamente para saveModel (evita erro "Título e conteúdo são obrigatórios" causado por state assíncrono)' },
  { version: '1.36.0', feature: '🎉 TypeScript strict mode COMPLETO - Zero errors (tsc --noEmit passa), migração de ~930 erros concluída, tipos alinhados, null safety' },
  { version: '1.35.89', feature: 'TypeScript FASE 8.7: Tipagem de event handlers (KeyboardEvent para ESC handlers, StorageEvent para multi-tab sync, CustomEvent para spacing/fontSize) - erros TS7006: 930→711' },
  { version: '1.35.88', feature: 'TypeScript Migration FASE 8.7: Tipagem de callAI/callLLM/callGemini, buildApiRequest, convertToGeminiFormat, extractTokenMetrics, extractResponseText + propriedades adicionais em AICallOptions + AIMessageContent import' },
  { version: '1.35.87', feature: 'TypeScript Migration FASE 8.7 (parcial): Tipagem completa de AIModelService, EmbeddingsService, JurisEmbeddingsService, EmbeddingsCDNService + callbacks do useAIIntegration (930→775 erros TS7006)' },
  { version: '1.35.86', feature: 'TypeScript Migration FASE 8.6: Tipagem de 84 useRef<T> - timers (ReturnType<typeof setTimeout>), DOM refs (HTMLDivElement, HTMLInputElement), Quill instances, callbacks, caches (Map<K,V>)' },
  { version: '1.35.85', feature: 'TypeScript Migration FASE 8.1-8.5: +20 tipos em src/types/index.ts (TextPreviewState, ToastState, SlashMenuState, ProgressState, PastedText, ChatMessage, Precedente, Artigo, etc.) + useState com objetos/arrays/null tipados' },
  { version: '1.35.80', feature: 'TypeScript Migration: prompts migrados (system.ts, ai-prompts.ts, meta-prompts.ts) + barrel exports em src/prompts/index.ts' },
  { version: '1.35.79', feature: 'TypeScript Migration FASE 5: App.jsx → App.tsx (~35000 linhas) - build OK, 503 testes passando' },
  { version: '1.35.78', feature: 'TypeScript Migration FASE 1-4: 11 hooks migrados (useModalManager, useFieldVersioning, useLocalStorage, useModelPreview, useTopicManager, useModelLibrary, useAIIntegration, useProofManager, useAuthMagicLink, useSyncManager, useCloudSync) + src/types/index.ts com 40+ tipos core' },
  { version: '1.35.77', feature: 'Gerar Estilo de Redação a partir de exemplos: botão "Gerar a partir de exemplos" no campo Estilo de Redação Personalizado - IA analisa sentenças do juiz e extrai TOM/VOCABULÁRIO/RITMO (buildStyleMetaPrompt)' },
  { version: '1.35.76', feature: 'Estilo Personalizado Substitutivo: AI_INSTRUCTIONS refatorado em CORE/STYLE/SAFETY - customPrompt do juiz SUBSTITUI (não complementa) o estilo default, evitando conflitos como "Use latinismos" vs "Evite latinismos"' },
  { version: '1.35.75', feature: 'UX: Feedback inline no botão Testar API Key - mostra ✓ (verde) ou ✗ (vermelho) por 2s ao invés de toast popup' },
  { version: '1.35.74', feature: 'Config IA Local exportada no projeto + apiKeys excluída do export (segurança): 8 campos movidos de localStorage para aiSettings, migração automática, preserva apiKeys do usuário no import' },
  { version: '1.35.73', feature: 'Fix header opaco no ModelGeneratorModal: conteúdo não vaza por baixo ao fazer scroll (theme-bg-primary 100% + backdrop-blur)' },
  { version: '1.35.72', feature: 'ModelGeneratorModal segue padrão BaseModal: ESC handler com stopPropagation (fecha modal correto), scroll lock' },
  { version: '1.35.71', feature: 'Fix z-index ModelGeneratorModal (z-100 > CSS.modalOverlay z-90) - modal abre acima do ConfigModal' },
  { version: '1.35.70', feature: '(tentativa anterior z-70 insuficiente)' },
  { version: '1.35.69', feature: 'Gerador Automático de Prompts: juiz cola exemplos → IA gera prompt profissional que reproduz seu estilo (meta-prompts.ts, ModelGeneratorModal.tsx)' },
  { version: '1.35.68', feature: 'Fix: botão X posicionado corretamente no TextPreviewModal (flex no header) e ModelPreviewModal (classe padronizada para tema claro)' },
  { version: '1.35.67', feature: 'UX: 4 modais migrados para padrão BaseModal (TextPreviewModal, ModelPreviewModal, Download de Dados, Download de Embeddings) - ESC handler, scroll lock, glassmorphism' },
  { version: '1.35.66', feature: 'UX: Modal "Excluir Toda Legislação" migrado para BaseModal (ESC handler, botão X, scroll lock, glassmorphism)' },
  { version: '1.35.65', feature: 'UX: VoiceButton movido para linha dos botões Jurisprudência/Assistente IA no editor global (FieldEditor prop hideVoiceButton)' },
  { version: '1.35.64', feature: 'UX: JurisprudenciaModal, AIAssistantBaseLegacy e ConfigModal seguem padrão BaseModal (ESC handler, botão X, scroll lock, glassmorphism)' },
  { version: '1.35.63', feature: 'UX: BaseModal bloqueia scroll do body quando aberto (evita scroll da página por baixo)' },
  { version: '1.35.62', feature: 'VoiceButton corrigido: removido de título/keywords, adicionado no editor global (FieldEditor) e assistente IA de modelos (AIAssistantBaseLegacy)' },
  { version: '1.35.61', feature: 'VoiceButton expandido: editor de modelos (QuillModelEditor) e Quick Edit (ModelPreviewModal)' },
  { version: '1.35.60', feature: 'Voice-to-Text Preview Flutuante: tooltip mostra texto em tempo real enquanto fala, só insere no editor quando resultado é final (feedback instantâneo)' },
  { version: '1.35.59', feature: 'Voice-to-Text: ditado por voz via Web Speech API nos editores de decisão, instruções para IA e chat do assistente (useVoiceToText hook + VoiceButton componente)' },
  { version: '1.35.58', feature: 'Worker Error Handling: onerror handler para rejeitar promises pendentes, timeout de 60s nas chamadas, método cleanup() para reset do AIModelService' },
  { version: '1.35.57', feature: 'UX: botão Sair movido para a mesma linha do botão Projeto (layout mais compacto)' },
  { version: '1.35.56', feature: 'Fix: botão Sair volta para o header (logout geral do sistema), apenas indicador + email ficam na aba Modelos' },
  { version: '1.35.55', feature: 'Bloco de sync de modelos (indicador + email) movido do header para a aba Modelos' },
  { version: '1.35.54', feature: 'Foto do perfil Google exibida no status de conexão Drive (ao lado do email)' },
  { version: '1.35.53', feature: 'UX: ícone Cloud preenchido (sólido) quando conectado ao Google Drive - contraste visual claro' },
  { version: '1.35.52', feature: 'UI consolidada: botão "Limpar Projeto" também incorporado ao dropdown (único botão "Projeto" no header)' },
  { version: '1.35.51', feature: 'UI consolidada: botões Salvar/Carregar Projeto movidos para dropdown "Projeto" (seções Google Drive + Local em um único lugar)' },
  { version: '1.35.50', feature: 'Google Drive migrado para TypeScript: useGoogleDrive.ts e GoogleDriveButton.tsx com interfaces tipadas (convenção de novos arquivos)' },
  { version: '1.35.49', feature: 'UX Polish: remover opção de permissão no compartilhamento Drive (sempre cópia), texto "Modelos sincronizados" mais claro, fix contraste tags categoria no tema claro' },
  { version: '1.35.48', feature: 'Google Drive: fix compartilhamento - arquivos compartilhados agora aparecem (sharedWithMe), botão para remover acesso no modal de permissões' },
  { version: '1.35.47', feature: 'Google Drive: arquivos salvos na pasta "Sentencify" (criada automaticamente) para melhor organização' },
  { version: '1.35.46', feature: 'Google Drive: filtrar por appProperties - mostra apenas arquivos criados pelo Sentencify (ignora compartilhamentos externos)' },
  { version: '1.35.45', feature: 'Google Drive compartilhamento corrigido: escopo drive.readonly permite ver arquivos de outros, badges "De: fulano" e "Compartilhado", modal de permissões' },
  { version: '1.35.44', feature: 'Header COOP (Cross-Origin-Opener-Policy) no servidor: elimina warning do Google OAuth popup no console' },
  { version: '1.35.43', feature: 'Compartilhar arquivos do Google Drive: botão para enviar por email com permissão de visualização ou edição' },
  { version: '1.35.42', feature: 'Fix erro React #31: notificações do Google Drive agora suportam objeto {type, message} (sucesso em verde, erro em vermelho)' },
  { version: '1.35.41', feature: 'Refatoração: exportProject e importProject usam buildProjectJson/importProjectFromJson (elimina ~200 linhas duplicadas)' },
  { version: '1.35.40', feature: 'Google Drive: salvar e carregar projetos na nuvem pessoal do usuário (OAuth2, sem custo adicional, até 750GB/dia)' },
  { version: '1.35.39', feature: 'Calibra estimativa de custo: constantes de tokens ajustadas com dados reais (BASE_CONTEXT 8K→3.5K, OUTPUT 3.5K→1.8K, GEMINI_THINKING ~50%)' },
  { version: '1.35.38', feature: 'Fix lag drag no modal: DragOverlay via createPortal(body) escapa CSS do modal, CSS.Translate para melhor performance, TopicCardVisual componente visual puro' },
  { version: '1.35.37', feature: 'Estimativa de custo melhorada: considera thinking tokens (Claude/Gemini), batch size (topicsPerRequest), tooltip com breakdown detalhado' },
  { version: '1.35.36', feature: 'Fix drag lag: remover willChange dinâmico (causava repaints contínuos), distance 8px (igual App.jsx)' },
  { version: '1.35.35', feature: 'Otimização drag FPS: React.memo no TopicPreviewCard, callbacks com setter funcional (sem dependências)' },
  { version: '1.35.34', feature: 'TopicCurationModal UX: modal não pode ser fechado (sem X, ESC, backdrop), largura 80vw, undo restaura no índice correto, custo exibe modelo (ex: R$ 1.04 Gemini 3 Flash)' },
  { version: '1.35.33', feature: 'TypeScript incremental: TopicCurationModal.tsx como primeiro arquivo .tsx (tsconfig.json com allowJs: true)' },
  { version: '1.35.32', feature: 'Fix z-index TopicCurationModal: aparece acima do AnalysisModal (z-[100] vs z-[90])' },
  { version: '1.35.31', feature: 'Testes TopicCurationModal (49 testes): renderização, callbacks, edição inline, exclusão, mesclagem, separação, adição, estimativa de custo, tópicos especiais' },
  { version: '1.35.30', feature: 'Modal de Curadoria de Tópicos: revisar, reordenar, mesclar, separar e apagar tópicos ANTES de gerar mini-relatórios (economia de tokens, estimativa de custo R$/tempo)' },
  { version: '1.35.29', feature: 'Fix meta-comentários de revisão nos mini-relatórios: prompt proíbe textos como "Revisei esta resposta..." + pós-processamento remove automaticamente (com log no console)' },
  { version: '1.35.28', feature: 'Fix testes E2E no CI: useAuth retorna early se localStorage tem sessão (evita timeout esperando servidor)' },
  { version: '1.35.27', feature: 'Testes de prompts agora usam AI_PROMPTS real (corrige MOCK_PROMPTS perigoso que não detectava mudanças)' },
  { version: '1.35.26', feature: 'Prompts de IA (AI_INSTRUCTIONS, AI_PROMPTS) movidos para src/prompts/ (~900 linhas extraídas do App.jsx)' },
  { version: '1.35.25', feature: 'CHANGELOG movido para src/constants/changelog.js (reduz clutter no App.jsx)' },
  { version: '1.35.24', feature: 'Fix B8b: sync remove modelos de owners sem acesso ativo (sharedLibraries filtra modelos locais compartilhados)' },
  { version: '1.35.23', feature: 'Fix B8: remover share via UI limpa modelos da biblioteca + A7a: trackChangeBatch para importação em lote eficiente' },
  { version: '1.35.22', feature: 'Fix duplicar modelo compartilhado (agora cria cópia própria) + tratamento de conflitos de sync (pull após conflito, model_deleted, no_permission)' },
  { version: '1.35.21', feature: 'Fix modelos compartilhados sumiam após sync incremental: preservar locais quando servidor não retorna compartilhados' },
  { version: '1.35.20', feature: 'Fix progresso de download: usa tamanhos estimados como fallback quando Content-Length não disponível (streaming proxy)' },
  { version: '1.35.19', feature: 'Fix modelos compartilhados não apareciam após aceitar: comparar accepted_at com lastSyncAt para detectar shares recém-aceitos' },
  { version: '1.35.18', feature: 'Log de diagnóstico para rate limiting: IP, email e User-Agent em cada request de magic link' },
  { version: '1.35.17', feature: 'Fix rate limiter: trust proxy para Cloudflare/Render (antes todos IPs eram iguais)' },
  { version: '1.35.16', feature: 'Email com domínio verificado: sentencify.ia.br em vez de resend.dev' },
  { version: '1.35.15', feature: 'Fix E2E tests: remover setupAuth órfão (fixture já faz autenticação)' },
  { version: '1.35.14', feature: 'Labels explícitos para PDFs binários: antes de cada PDF, adiciona texto identificador para IA saber qual documento é qual' },
  { version: '1.35.13', feature: 'Rate limiting: proteção contra abuso (auth 10/15min, IA 30/min, geral 100/min)' },
  { version: '1.35.12', feature: 'Sentry error tracking: captura erros em produção (frontend + backend), alertas por email, stack traces completos' },
  { version: '1.35.11', feature: 'Fix sync: pull-then-push evita conflitos, retry com limit para conflitos de versão, shared filter por lastSyncAt, validação email no accept' },
  { version: '1.35.10', feature: 'Fix lag REAL: estado local bufferizado em ModelFormModal e AIRegenerationSection - digitação não propaga para LegalDecisionEditor (Análise Gemini)' },
  { version: '1.35.9', feature: 'Fix lag em TODOS inputs: todos os 11 setters de useAIIntegration convertidos para useCallback + useCloudSync.return memoizado com useMemo' },
  { version: '1.35.8', feature: 'Fix lag final: findSuggestions e refineWithAI agora usam useCallback (evita re-criação a cada render que quebrava React.memo)' },
  { version: '1.35.7', feature: 'Fix lag residual no "regenerar com IA": setRelatorioInstruction/setDispositivoInstruction agora usam useCallback (referência estável)' },
  { version: '1.35.6', feature: 'Fix lag no campo "regenerar com IA": removidas arrow functions inline em onInstructionChange (passando função direta)' },
  { version: '1.35.5', feature: 'Fix erro "Rendered more hooks" no ModelFormModal: hooks useCallback movidos para antes do return condicional' },
  { version: '1.35.4', feature: 'Fix lag causado por dependência circular no Cloud Sync: libraryModels nas deps do useEffect causava loop infinito de re-renders ao digitar' },
  { version: '1.35.3', feature: 'Fix lag de escrita nos editores: debounce 150ms no onChange/sanitização do Quill, memoização de getCategories, primitivos em isIndividualDirty' },
  { version: '1.35.2', feature: 'Fix exclusão em massa: deleteAllModels() agora rastreia cada modelo para sync; delete salva apenas id (evita QuotaExceededError no localStorage)' },
  { version: '1.35.1', feature: 'Compartilhamento por email: convite direto, edição colaborativa (edit permite editar/deletar originais), fix sync modelos deletados, fix typing lag' },
  { version: '1.35.0', feature: 'Compartilhamento de biblioteca: gerar link para compartilhar modelos (view/edit), badge de proprietário, filtro Meus/Compartilhados' },
  { version: '1.34.9', feature: 'Fix validação: aceita null em category/keywords (antes rejeitava modelos com campos opcionais null)' },
  { version: '1.34.8', feature: 'Fix cache IndexedDB: atualizado com modelos validados + log de modelos rejeitados para debug' },
  { version: '1.34.7', feature: 'Fix sync: salva IMEDIATAMENTE no IndexedDB após merge (debounce de 1500ms causava perda de dados)' },
  { version: '1.34.6', feature: 'Sync inteligente: compara contagem local vs servidor, força full sync se diferente' },
  { version: '1.34.5', feature: 'Fix race condition: merge de sync agora espera IndexedDB carregar (evita perda de modelos)' },
  { version: '1.34.4', feature: 'Admin Panel: interface /admin para gerenciar emails autorizados via Magic Link (protegida por senha)' },
  { version: '1.34.3', feature: 'Cloud Sync Full Sync + UPSERT: navegador novo baixa todos modelos, INSERT OR REPLACE evita conflitos' },
  { version: '1.34.2', feature: 'Cloud Sync Pull Paginado: 50 modelos por request evita crash de memória' },
  { version: '1.34.1', feature: 'Cloud Sync Pull Merge: modelos recebidos do servidor são mesclados com IndexedDB local' },
  { version: '1.34.0', feature: 'Cloud Sync: Magic Link Authentication + SQLite Sync - modelos salvos na nuvem (Render Persistent Disk)' },
  { version: '1.33.63', feature: 'Testes E2E expandidos (88 testes): auth, pdf-upload, generation, export, search' },
  { version: '1.33.62', feature: 'Modal "Sessão Anterior Encontrada" não pode ser fechado (ESC, X, click fora) - usuário deve escolher' },
  { version: '1.33.61', feature: 'Auto-download de dados: legislação e jurisprudência baixados automaticamente do GitHub Releases (~5 MB, download único)' },
  { version: '1.33.60', feature: 'Otimização drag: collision detection O(n) com Set pré-computado (antes O(n²) com find)' },
  { version: '1.33.59', feature: 'Fix drag feedback visual: collision detection customizado ignora RELATÓRIO/DISPOSITIVO' },
  { version: '1.33.58', feature: 'dnd-kit para drag and drop de tópicos - suporte a wheel scroll durante arraste' },
  { version: '1.33.57', feature: 'Modal estilizado para confirmação de logout (substituir window.confirm nativo)' },
  { version: '1.33.56', feature: 'Reduzir espaçamento entre cards no modo lista (space-y-1, itemHeight 90)' },
  { version: '1.33.55', feature: 'Fix borda superior cortada no hover do modo lista - remover card-hover-lift (translateY invadia card acima)' },
  { version: '1.33.54', feature: 'Fix borda sumindo no hover do modo lista (ModelCard) - border-2 para consistência com cards' },
  { version: '1.33.53', feature: 'Otimizar hover elevation - GPU acceleration (will-change, translateZ, transition específica)' },
  { version: '1.33.52', feature: 'Fix mensagens hardcoded no bulk upload - agora mostra valor real de parallelRequests' },
  { version: '1.33.51', feature: 'Modal changelog migrado para BaseModal (ESC para fechar + glassmorphism)' },
  { version: '1.33.50', feature: 'Micro-interações visuais: cards com hover elevação, badges fade-in, estrela favorito colorida, empty states pulsando, drag&drop suave, focus rings, spinner neon no app loading' },
  { version: '1.33.49', feature: 'Spinner Neon + Ripple no AnalysisModal (anéis girando com ondas pulsantes)' },
  { version: '1.33.48', feature: 'ESC handler centralizado no BaseModal (18 modais beneficiados)' },
  { version: '1.33.47', feature: 'Glassmorphism + ESC em 7 modais (ExtractModel, AIAssistant, Analysis, Dispositivo, Similarity, Config)' },
  { version: '1.33.46', feature: 'Aplicar estilo Glassmorphism ao BulkUploadModal (consistência visual)' },
  { version: '1.33.45', feature: 'Migrar ProofAnalysisModal e LinkProofModal para BaseModal (padronização UI)' },
  { version: '1.33.44', feature: 'Fix título e botão X dos modais no tema claro' },
  { version: '1.33.43', feature: 'Fix modais: tema claro respeitado, transparência adequada, glow adaptativo' },
  { version: '1.33.42', feature: 'Modais com estilo Glassmorphism: blur, gradientes, ícones em círculos, botão X, animação suave' },
  { version: '1.33.41', feature: 'Autenticação simples: tela de login, senha hasheada (SHA-256), botão Sair no header' },
  { version: '1.33.40', feature: 'Validação de PDFs (33 testes): magic bytes, tamanho, tipo, estimativa de tempo de processamento' },
  { version: '1.33.39', feature: 'Testes de regressão de prompts (21 testes snapshot): validação de estrutura, Art. 337 CPC, ordem do mérito' },
  { version: '1.33.38', feature: 'Testes de integração (71 testes): topicOrdering, analyzeProof, generateSentence + utilitários extraídos em src/utils' },
  { version: '1.33.37', feature: 'Comentários padronizados: 9 seções com bordas ═══ e descrições (IMPORTS, UTILITÁRIOS, HOOKS, UI, MODAIS, QUILL, AI_PROMPTS, LEGALDECISIONEDITOR, ERROR BOUNDARY)' },
  { version: '1.33.36', feature: 'Índice/mapa estruturado no topo do arquivo: navegação rápida para LLMs, 9 seções mapeadas, fluxos críticos documentados' },
  { version: '1.33.35', feature: 'Ordenação v3: numeração única (6a-6f), sem referências cruzadas, explicações contextuais mantidas' },
  { version: '1.33.34', feature: 'Ordenação v2: 7 grupos (tramitação, preliminares, prejudiciais, mérito, finais) + ordem lógica do mérito (CAUSA > OBRIGAÇÃO > EFEITO)' },
  { version: '1.33.33', feature: 'Ordenação de preliminares conforme Art. 337 CPC (13 incisos na ordem legal)' },
  { version: '1.33.32', feature: 'Fix embeddings 502: streaming com Readable.fromWeb() evita OOM no Render free tier (512MB RAM)' },
  { version: '1.33.31', feature: 'Migração para Render: sem limite de payload (100MB vs 4.5MB Vercel), heartbeat keepalive, timeout 100min' },
  { version: '1.33.30', feature: 'Testes sanitizeHTML expandidos (39 testes XSS) - total 285 testes (261 unit + 24 E2E)' },
  { version: '1.33.29', feature: 'Testes E2E expandidos (24 testes) - total 267 testes (243 unit + 24 E2E)' },
  { version: '1.33.28', feature: 'Testes useTopicManager (42 testes) - total 243 testes unitários' },
  { version: '1.33.27', feature: 'Reverter useModalManager para App.jsx (consistência: todos hooks no mesmo padrão)' },
  { version: '1.33.26', feature: 'Refatorar useModalManager para arquivo separado (melhor testabilidade)' },
  { version: '1.33.25', feature: 'Fix setState durante render: contextualInsertFn como ref em useModelPreview' },
  { version: '1.33.24', feature: 'Fix HTML nesting warning: spinner div→span no GlobalEditorModal' },
  { version: '1.33.23', feature: 'Fix infinite loop: ref para handleInsertModel em GlobalEditorModal' },
  { version: '1.33.22', feature: 'Fix infinite loop: useMemo em useFieldVersioning e useModelPreview' },
  { version: '1.33.21', feature: 'Fix botão limpar formatação (usa format(key,false) em vez de removeFormat)' },
  { version: '1.33.20', feature: 'Fix botão limpar formatação + toggle semântico por padrão + badge similaridade sempre visível' },
  { version: '1.33.19', feature: 'Botão limpar formatação no editor + toggle 🧠/🔤 semântico na busca manual de modelos' },
  { version: '1.33.18', feature: 'Badge % similaridade em jurisprudência e modelos sugeridos (modo semântico)' },
  { version: '1.33.17', feature: 'Fix modal jurisprudência: sincronizar toggle com config IA Local ao abrir' },
  { version: '1.33.16', feature: 'Modal jurisprudência: badge 🤖 IA Local + toggle 🧠/🔤 semântico/textual' },
  { version: '1.33.15', feature: 'Fix batchSize hardcoded em mini-relatórios/subtópicos + contraste "Erro 429" no tema escuro' },
  { version: '1.33.14', feature: 'Fix NER: indexOf case-insensitive, dedup inclui entityType, fallback ORG limitado a 4 palavras + normaliza espaços' },
  { version: '1.33.13', feature: 'NER healing: subtokens órfãos (##edo) unidos ao prefixo (Mac→Macedo) + fallback regex para ORG (V2 LTDA)' },
  { version: '1.33.12', feature: 'Fix contraste do aviso de erro 429 no tema claro' },
  { version: '1.33.11', feature: 'Requisições paralelas configuráveis: escolha 3-20 em Config IA, com explicativo de limites por API/tier' },
  { version: '1.33.10', feature: 'Tooltip no SlashCommand mostra modelo completo (não truncado)' },
  { version: '1.33.9', feature: 'Fix contraste do badge de similaridade no SlashCommand (tema claro)' },
  { version: '1.33.8', feature: 'SlashCommand melhorado: posicionamento viewport-aware, tooltip preview, busca semântica, hover corrigido nos toggles 🧠' },
  { version: '1.33.7', feature: 'Feedback visual ao duplicar modelo: toast "Duplicando..." durante geração de embedding' },
  { version: '1.33.6', feature: 'Layout 1 card por linha em toda aba Modelos (busca textual + inicial)' },
  { version: '1.33.5', feature: 'Layout 1 card por linha na busca semântica de modelos' },
  { version: '1.33.4', feature: 'Unificar UI busca semântica de modelos: usar ModelCard com editar/duplicar/excluir, respeitar modo cards/lista, badge de similaridade' },
  { version: '1.33.3', feature: 'Feedback visual "Salvando..." no SimilarityWarningModal durante geração de embedding' },
  { version: '1.33.2', feature: 'Remover logs de AI/Search em produção (apenas em DEV)' },
  { version: '1.33.1', feature: 'Fix CORS: proxy serverless para download embeddings, UI simplificada (remove import manual), z-index modal corrigido' },
  { version: '1.33.0', feature: 'Auto-download de embeddings via CDN: legislação e jurisprudência baixados automaticamente do GitHub Releases (~250MB)' },
  { version: '1.32.42', feature: 'Migrar Tailwind CDN para PostCSS: build-time compilation, remove warning de produção, CSS otimizado' },
  { version: '1.32.41', feature: 'Suporte a deploy Vercel: serverless functions (/api/claude, /api/gemini), API_BASE dinâmico (local vs prod)' },
  { version: '1.32.40', feature: 'Toggle para ativar/desativar logs de thinking no console (Config IA > Log thinking no console)' },
  { version: '1.32.39', feature: 'Log de thinking no console do browser: Claude (extended thinking) e Gemini 3 (includeThoughts) para debug e análise' },
  { version: '1.32.38', feature: 'Gemini thinking buffer: auto-aumenta maxOutputTokens baseado no thinking_level (high +16K, medium +8K, low +4K, minimal +2K)' },
  { version: '1.32.37', feature: 'Fix Gemini 3 Pro: validar thinking_level (Pro só suporta low/high, minimal/medium convertidos para low)' },
  { version: '1.32.36', feature: 'Removido Gemini 2.5: apenas Gemini 3 Flash/Pro disponíveis, UI simplificada (thinking_level apenas)' },
  { version: '1.32.35', feature: 'Fix Gemini thinking: extração de texto agora busca part sem thought=true (antes pegava parts[0] que era thinking)' },
  { version: '1.32.34', feature: 'Fix reorderTopicsViaLLM: regex mais robusto (suporta markdown code blocks, newlines no JSON)' },
  { version: '1.32.33', feature: 'Auto-timeout 5 min para thinking budgets >= 40K + warning "respostas podem demorar mais"' },
  { version: '1.32.32', feature: 'Budget thinking dinâmico por modelo Claude: Sonnet até 62K, Opus até 30K + warning para budgets >= 40K (risco timeout)' },
  { version: '1.32.31', feature: 'UI Gemini 2.5 Pro: toggle mostra "Mínimo" + badge "1024 tokens" quando thinking "desativado" (API não permite desligar)' },
  { version: '1.32.30', feature: 'Fix thinking config: Gemini 2.5 Flash agora desativa thinking com budget 0 (antes usava dinâmico), 2.5 Pro usa mínimo' },
  { version: '1.32.29', feature: 'Fix crítico Gemini: useInstructions agora envia AI_INSTRUCTIONS como systemInstruction (13 funcionalidades corrigidas)' },
  { version: '1.32.28', feature: 'Chat assistente: verificação obrigatória - LLM deve listar informações pendentes ANTES de redigir' },
  { version: '1.32.27', feature: 'Chat assistente: instrução de perguntas fortalecida - "prefira perguntar a presumir"' },
  { version: '1.32.26', feature: 'Chat assistente: maxTokens 16000 + log finishReason no servidor Gemini' },
  { version: '1.32.25', feature: 'Fix reorderTopicsViaLLM: regex robusto + maxTokens 4000 (evita truncamento com Gemini 3)' },
  { version: '1.32.24', feature: 'Modal de changelog ao clicar na versão' },
  { version: '1.32.23', feature: 'Títulos de tópicos com causa de pedir nuclear: prompt ajustado para gerar títulos como "RESCISÃO INDIRETA - ASSÉDIO MORAL"' },
  { version: '1.32.22', feature: 'Sugestões de modelos usando apenas título: embedding da query usa só topic.title' },
  { version: '1.32.21', feature: 'Filtros antes do limit: filtros de tipo/tribunal aplicados ANTES de limitar em 30 resultados' },
  { version: '1.32.20', feature: 'Fix case sensitivity E5: queries convertidas para toLowerCase()' },
  { version: '1.32.19', feature: 'Fix busca semântica no modal de jurisprudência' },
  { version: '1.32.18', feature: 'Busca semântica de jurisprudência nos editores' },
  { version: '1.32.17', feature: 'NER sob demanda: modelo carrega só ao clicar "Detectar Nomes"' },
  { version: '1.32.16', feature: 'Botões responsivos na aba Tópicos' },
  { version: '1.32.15', feature: 'Tesseract alta qualidade: SCALE 4.0 + PSM 6' },
  { version: '1.32.14', feature: 'Fix Tesseract em Provas' },
  { version: '1.32.13', feature: 'Permitir Tesseract com anonimização' },
  { version: '1.32.12', feature: 'Fix mergeOrgLoc: aceita ORG+ORG curto' },
  { version: '1.32.11', feature: 'Botão Manual do Usuário (📖) no header' },
  { version: '1.32.10', feature: 'NER fusão ORG+LOC' },
  { version: '1.32.09', feature: 'Fix NER modelo: BERT completo' },
  { version: '1.32.08', feature: 'IA Local via Web Worker' },
  { version: '1.32.07', feature: 'Fix NER separação de nomes' },
  { version: '1.32.06', feature: 'Auto-inicialização modelos NER/E5' },
  { version: '1.32.00', feature: 'IA Local Refatoração: Web Worker, modelos HuggingFace' },
  { version: '1.31.04', feature: 'IA Local Otimização: SIMD/threads/WebGPU' },
  { version: '1.31.00', feature: 'Tesseract.js OCR Offline' },
  { version: '1.30.00', feature: 'Gemini Vision OCR' },
  { version: '1.29.00', feature: 'NER incluir ORG (empresas)' },
  { version: '1.28.02', feature: 'Sugestões de modelos via IA Local' },
  { version: '1.28.00', feature: 'Remoção da geração inline de embeddings' },
  { version: '1.27.00', feature: 'Busca Semântica na Jurisprudência' },
  { version: '1.26.00', feature: 'Busca Semântica na Legislação' },
  { version: '1.25.17', feature: 'Fuzzy Deduplication para nomes' },
  { version: '1.25.02', feature: 'IA Offline NER' },
  { version: '1.25.00', feature: 'Otimização de cache (economia ~40-50% tokens)' },
  { version: '1.24.00', feature: 'Sistema de Versionamento do campo fundamentação' },
  { version: '1.22.00', feature: 'Centralização prompts mini-relatórios' },
  { version: '1.21.21', feature: 'Botão "Revisar Sentença"' },
  { version: '1.21.20', feature: 'Filtro "Informativo" na jurisprudência' },
  { version: '1.21.00', feature: 'Anonimização completa provas' },
  { version: '1.20.00', feature: 'Fix duplicação tópicos + VirtualList' },
  { version: '1.19.00', feature: 'Chat interativo no assistente IA' },
  { version: '1.14.00', feature: 'Detecção TF-IDF de similaridade' },
];
